spring:
  datasource:
#    url: jdbc:mysql://18.141.121.141:3306/libiaotest?useSSL=false
    url: jdbc:mysql://localhost:3306/libiaotest?useSSL=false
    username: root
#    password: libiao123
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
#    host: 18.141.121.141
    host: localhost
    port: 6379
    database: 0
#    password: libiao6878*

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB

mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

swagger:
  show: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


