
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/libiao?allowMultiQueries=true
    username: libiao
    password: LiBiao@#$%.321
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0
    password: libiao@2023

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB

mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

swagger:
  show: true

CONTRACT_PATH: ${user.home}/contract/
BILL_PATH: ${user.home}/bill/
SAMPLE_PATH: ${user.home}/sample/
RECORD_PATH: ${user.home}/record/

pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
logging:
  config: classpath:logback-spring.xml
  level:
    com.libiao.customer.dal.mapper: debug

