package com.libiao.customer.dal.model;

import java.io.Serializable;

public class BasicStandard implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_standard.id
     *
     * @mbg.generated Sun Jan 01 15:39:49 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_standard.name
     *
     * @mbg.generated Sun Jan 01 15:39:50 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_standard.method
     *
     * @mbg.generated Sun Jan 01 15:39:50 CST 2023
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_standard.item
     *
     * @mbg.generated Sun Jan 01 15:39:50 CST 2023
     */
    private String item;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_standard.type
     *
     * @mbg.generated Sun Jan 01 15:39:50 CST 2023
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table basic_standard
     *
     * @mbg.generated Sun Jan 01 15:39:50 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_standard.id
     *
     * @return the value of basic_standard.id
     *
     * @mbg.generated Sun Jan 01 15:39:49 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_standard.id
     *
     * @param id the value for basic_standard.id
     *
     * @mbg.generated Sun Jan 01 15:39:50 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_standard.name
     *
     * @return the value of basic_standard.name
     *
     * @mbg.generated Sun Jan 01 15:39:50 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_standard.name
     *
     * @param name the value for basic_standard.name
     *
     * @mbg.generated Sun Jan 01 15:39:50 CST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_standard.method
     *
     * @return the value of basic_standard.method
     *
     * @mbg.generated Sun Jan 01 15:39:50 CST 2023
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_standard.method
     *
     * @param method the value for basic_standard.method
     *
     * @mbg.generated Sun Jan 01 15:39:50 CST 2023
     */
    public void setMethod(String method) {
        this.method = method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_standard.item
     *
     * @return the value of basic_standard.item
     *
     * @mbg.generated Sun Jan 01 15:39:50 CST 2023
     */
    public String getItem() {
        return item;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_standard.item
     *
     * @param item the value for basic_standard.item
     *
     * @mbg.generated Sun Jan 01 15:39:50 CST 2023
     */
    public void setItem(String item) {
        this.item = item;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_standard.type
     *
     * @return the value of basic_standard.type
     *
     * @mbg.generated Sun Jan 01 15:39:50 CST 2023
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_standard.type
     *
     * @param type the value for basic_standard.type
     *
     * @mbg.generated Sun Jan 01 15:39:50 CST 2023
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_standard
     *
     * @mbg.generated Sun Jan 01 15:39:50 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", method=").append(method);
        sb.append(", item=").append(item);
        sb.append(", type=").append(type);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}