package com.libiao.customer.dal.model;

import java.io.Serializable;

public class BasicStandard implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_standard.id
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_standard.name
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_standard.ext1
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    private String ext1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_standard.ext2
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    private String ext2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_standard.ext3
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    private String ext3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_standard.ext4
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    private String ext4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_standard.ext5
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    private String ext5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table basic_standard
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_standard.id
     *
     * @return the value of basic_standard.id
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_standard.id
     *
     * @param id the value for basic_standard.id
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_standard.name
     *
     * @return the value of basic_standard.name
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_standard.name
     *
     * @param name the value for basic_standard.name
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_standard.ext1
     *
     * @return the value of basic_standard.ext1
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_standard.ext1
     *
     * @param ext1 the value for basic_standard.ext1
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_standard.ext2
     *
     * @return the value of basic_standard.ext2
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_standard.ext2
     *
     * @param ext2 the value for basic_standard.ext2
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_standard.ext3
     *
     * @return the value of basic_standard.ext3
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    public String getExt3() {
        return ext3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_standard.ext3
     *
     * @param ext3 the value for basic_standard.ext3
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_standard.ext4
     *
     * @return the value of basic_standard.ext4
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    public String getExt4() {
        return ext4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_standard.ext4
     *
     * @param ext4 the value for basic_standard.ext4
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    public void setExt4(String ext4) {
        this.ext4 = ext4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_standard.ext5
     *
     * @return the value of basic_standard.ext5
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    public String getExt5() {
        return ext5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_standard.ext5
     *
     * @param ext5 the value for basic_standard.ext5
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    public void setExt5(String ext5) {
        this.ext5 = ext5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_standard
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", ext1=").append(ext1);
        sb.append(", ext2=").append(ext2);
        sb.append(", ext3=").append(ext3);
        sb.append(", ext4=").append(ext4);
        sb.append(", ext5=").append(ext5);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}