package com.libiao.customer.dal.model;

import java.io.Serializable;

public class BasicTestInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_test_info.id
     *
     * @mbg.generated Mon Jan 02 16:00:25 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_test_info.test_method
     *
     * @mbg.generated Mon Jan 02 16:00:25 CST 2023
     */
    private String testMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_test_info.test_case
     *
     * @mbg.generated Mon Jan 02 16:00:25 CST 2023
     */
    private String testCase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_test_info.limit_value
     *
     * @mbg.generated Mon Jan 02 16:00:25 CST 2023
     */
    private Integer limitValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table basic_test_info
     *
     * @mbg.generated Mon Jan 02 16:00:25 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_test_info.id
     *
     * @return the value of basic_test_info.id
     *
     * @mbg.generated Mon Jan 02 16:00:25 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_test_info.id
     *
     * @param id the value for basic_test_info.id
     *
     * @mbg.generated Mon Jan 02 16:00:25 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_test_info.test_method
     *
     * @return the value of basic_test_info.test_method
     *
     * @mbg.generated Mon Jan 02 16:00:25 CST 2023
     */
    public String getTestMethod() {
        return testMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_test_info.test_method
     *
     * @param testMethod the value for basic_test_info.test_method
     *
     * @mbg.generated Mon Jan 02 16:00:25 CST 2023
     */
    public void setTestMethod(String testMethod) {
        this.testMethod = testMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_test_info.test_case
     *
     * @return the value of basic_test_info.test_case
     *
     * @mbg.generated Mon Jan 02 16:00:25 CST 2023
     */
    public String getTestCase() {
        return testCase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_test_info.test_case
     *
     * @param testCase the value for basic_test_info.test_case
     *
     * @mbg.generated Mon Jan 02 16:00:25 CST 2023
     */
    public void setTestCase(String testCase) {
        this.testCase = testCase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_test_info.limit_value
     *
     * @return the value of basic_test_info.limit_value
     *
     * @mbg.generated Mon Jan 02 16:00:25 CST 2023
     */
    public Integer getLimitValue() {
        return limitValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_test_info.limit_value
     *
     * @param limitValue the value for basic_test_info.limit_value
     *
     * @mbg.generated Mon Jan 02 16:00:25 CST 2023
     */
    public void setLimitValue(Integer limitValue) {
        this.limitValue = limitValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_test_info
     *
     * @mbg.generated Mon Jan 02 16:00:25 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", testMethod=").append(testMethod);
        sb.append(", testCase=").append(testCase);
        sb.append(", limitValue=").append(limitValue);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}