package com.libiao.customer.dal.model;

import java.io.Serializable;

public class BasicGoodsMaterial implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_goods_material.id
     *
     * @mbg.generated Fri Jan 06 16:37:08 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_goods_material.class_id
     *
     * @mbg.generated Fri Jan 06 16:37:08 CST 2023
     */
    private Integer classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_goods_material.material_name
     *
     * @mbg.generated Fri Jan 06 16:37:08 CST 2023
     */
    private String materialName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table basic_goods_material
     *
     * @mbg.generated Fri Jan 06 16:37:08 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_goods_material.id
     *
     * @return the value of basic_goods_material.id
     *
     * @mbg.generated Fri Jan 06 16:37:08 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_goods_material.id
     *
     * @param id the value for basic_goods_material.id
     *
     * @mbg.generated Fri Jan 06 16:37:08 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_goods_material.class_id
     *
     * @return the value of basic_goods_material.class_id
     *
     * @mbg.generated Fri Jan 06 16:37:08 CST 2023
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_goods_material.class_id
     *
     * @param classId the value for basic_goods_material.class_id
     *
     * @mbg.generated Fri Jan 06 16:37:08 CST 2023
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_goods_material.material_name
     *
     * @return the value of basic_goods_material.material_name
     *
     * @mbg.generated Fri Jan 06 16:37:08 CST 2023
     */
    public String getMaterialName() {
        return materialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_goods_material.material_name
     *
     * @param materialName the value for basic_goods_material.material_name
     *
     * @mbg.generated Fri Jan 06 16:37:08 CST 2023
     */
    public void setMaterialName(String materialName) {
        this.materialName = materialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_goods_material
     *
     * @mbg.generated Fri Jan 06 16:37:08 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", classId=").append(classId);
        sb.append(", materialName=").append(materialName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}