package com.libiao.customer.dal.model;

import java.io.Serializable;
import java.util.Date;

public class DepartmentOrg implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department_org.org_no
     *
     * @mbg.generated Wed Dec 28 17:10:50 CST 2022
     */
    private String orgNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department_org.org_name
     *
     * @mbg.generated Wed Dec 28 17:10:50 CST 2022
     */
    private String orgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department_org.parent_org_no
     *
     * @mbg.generated Wed Dec 28 17:10:50 CST 2022
     */
    private String parentOrgNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department_org.person_in_charge
     *
     * @mbg.generated Wed Dec 28 17:10:50 CST 2022
     */
    private Long personInCharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department_org.city
     *
     * @mbg.generated Wed Dec 28 17:10:50 CST 2022
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department_org.create_time
     *
     * @mbg.generated Wed Dec 28 17:10:50 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department_org.create_by
     *
     * @mbg.generated Wed Dec 28 17:10:50 CST 2022
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table department_org
     *
     * @mbg.generated Wed Dec 28 17:10:50 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department_org.org_no
     *
     * @return the value of department_org.org_no
     *
     * @mbg.generated Wed Dec 28 17:10:50 CST 2022
     */
    public String getOrgNo() {
        return orgNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department_org.org_no
     *
     * @param orgNo the value for department_org.org_no
     *
     * @mbg.generated Wed Dec 28 17:10:50 CST 2022
     */
    public void setOrgNo(String orgNo) {
        this.orgNo = orgNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department_org.org_name
     *
     * @return the value of department_org.org_name
     *
     * @mbg.generated Wed Dec 28 17:10:50 CST 2022
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department_org.org_name
     *
     * @param orgName the value for department_org.org_name
     *
     * @mbg.generated Wed Dec 28 17:10:50 CST 2022
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department_org.parent_org_no
     *
     * @return the value of department_org.parent_org_no
     *
     * @mbg.generated Wed Dec 28 17:10:50 CST 2022
     */
    public String getParentOrgNo() {
        return parentOrgNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department_org.parent_org_no
     *
     * @param parentOrgNo the value for department_org.parent_org_no
     *
     * @mbg.generated Wed Dec 28 17:10:50 CST 2022
     */
    public void setParentOrgNo(String parentOrgNo) {
        this.parentOrgNo = parentOrgNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department_org.person_in_charge
     *
     * @return the value of department_org.person_in_charge
     *
     * @mbg.generated Wed Dec 28 17:10:50 CST 2022
     */
    public Long getPersonInCharge() {
        return personInCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department_org.person_in_charge
     *
     * @param personInCharge the value for department_org.person_in_charge
     *
     * @mbg.generated Wed Dec 28 17:10:50 CST 2022
     */
    public void setPersonInCharge(Long personInCharge) {
        this.personInCharge = personInCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department_org.city
     *
     * @return the value of department_org.city
     *
     * @mbg.generated Wed Dec 28 17:10:50 CST 2022
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department_org.city
     *
     * @param city the value for department_org.city
     *
     * @mbg.generated Wed Dec 28 17:10:50 CST 2022
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department_org.create_time
     *
     * @return the value of department_org.create_time
     *
     * @mbg.generated Wed Dec 28 17:10:50 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department_org.create_time
     *
     * @param createTime the value for department_org.create_time
     *
     * @mbg.generated Wed Dec 28 17:10:50 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department_org.create_by
     *
     * @return the value of department_org.create_by
     *
     * @mbg.generated Wed Dec 28 17:10:50 CST 2022
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department_org.create_by
     *
     * @param createBy the value for department_org.create_by
     *
     * @mbg.generated Wed Dec 28 17:10:50 CST 2022
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_org
     *
     * @mbg.generated Wed Dec 28 17:10:50 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orgNo=").append(orgNo);
        sb.append(", orgName=").append(orgName);
        sb.append(", parentOrgNo=").append(parentOrgNo);
        sb.append(", personInCharge=").append(personInCharge);
        sb.append(", city=").append(city);
        sb.append(", createTime=").append(createTime);
        sb.append(", createBy=").append(createBy);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}