package com.libiao.customer.dal.model;

import java.io.Serializable;

public class GoodsItem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_item.goods_id
     *
     * @mbg.generated Thu Dec 29 09:42:15 CST 2022
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_item.item_id
     *
     * @mbg.generated Thu Dec 29 09:42:15 CST 2022
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods_item
     *
     * @mbg.generated Thu Dec 29 09:42:15 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_item.goods_id
     *
     * @return the value of goods_item.goods_id
     *
     * @mbg.generated Thu Dec 29 09:42:15 CST 2022
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_item.goods_id
     *
     * @param goodsId the value for goods_item.goods_id
     *
     * @mbg.generated Thu Dec 29 09:42:15 CST 2022
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_item.item_id
     *
     * @return the value of goods_item.item_id
     *
     * @mbg.generated Thu Dec 29 09:42:15 CST 2022
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_item.item_id
     *
     * @param itemId the value for goods_item.item_id
     *
     * @mbg.generated Thu Dec 29 09:42:15 CST 2022
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_item
     *
     * @mbg.generated Thu Dec 29 09:42:15 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", goodsId=").append(goodsId);
        sb.append(", itemId=").append(itemId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}