package com.libiao.customer.dal.model;

import java.io.Serializable;

public class MallGoods implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.id
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.goods_num
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    private String goodsNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.goods_name
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.price
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.description
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.hscode
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    private String hscode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.material
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    private String material;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.export
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    private String export;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.platform
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    private String platform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.standard
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    private String standard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.indust_class
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    private String industClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.bus_type
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    private Byte busType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.subtitle
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    private String subtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.attr1
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    private String attr1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.attr2
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    private String attr2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.attr3
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    private String attr3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.test_item_list
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    private String testItemList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.meal_list
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    private String mealList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mall_goods
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.id
     *
     * @return the value of mall_goods.id
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.id
     *
     * @param id the value for mall_goods.id
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.goods_num
     *
     * @return the value of mall_goods.goods_num
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public String getGoodsNum() {
        return goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.goods_num
     *
     * @param goodsNum the value for mall_goods.goods_num
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public void setGoodsNum(String goodsNum) {
        this.goodsNum = goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.goods_name
     *
     * @return the value of mall_goods.goods_name
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.goods_name
     *
     * @param goodsName the value for mall_goods.goods_name
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.price
     *
     * @return the value of mall_goods.price
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.price
     *
     * @param price the value for mall_goods.price
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public void setPrice(String price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.description
     *
     * @return the value of mall_goods.description
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.description
     *
     * @param description the value for mall_goods.description
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.hscode
     *
     * @return the value of mall_goods.hscode
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public String getHscode() {
        return hscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.hscode
     *
     * @param hscode the value for mall_goods.hscode
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public void setHscode(String hscode) {
        this.hscode = hscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.material
     *
     * @return the value of mall_goods.material
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public String getMaterial() {
        return material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.material
     *
     * @param material the value for mall_goods.material
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public void setMaterial(String material) {
        this.material = material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.export
     *
     * @return the value of mall_goods.export
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public String getExport() {
        return export;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.export
     *
     * @param export the value for mall_goods.export
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public void setExport(String export) {
        this.export = export;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.platform
     *
     * @return the value of mall_goods.platform
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.platform
     *
     * @param platform the value for mall_goods.platform
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public void setPlatform(String platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.standard
     *
     * @return the value of mall_goods.standard
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public String getStandard() {
        return standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.standard
     *
     * @param standard the value for mall_goods.standard
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public void setStandard(String standard) {
        this.standard = standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.indust_class
     *
     * @return the value of mall_goods.indust_class
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public String getIndustClass() {
        return industClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.indust_class
     *
     * @param industClass the value for mall_goods.indust_class
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public void setIndustClass(String industClass) {
        this.industClass = industClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.bus_type
     *
     * @return the value of mall_goods.bus_type
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public Byte getBusType() {
        return busType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.bus_type
     *
     * @param busType the value for mall_goods.bus_type
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public void setBusType(Byte busType) {
        this.busType = busType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.subtitle
     *
     * @return the value of mall_goods.subtitle
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.subtitle
     *
     * @param subtitle the value for mall_goods.subtitle
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.attr1
     *
     * @return the value of mall_goods.attr1
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public String getAttr1() {
        return attr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.attr1
     *
     * @param attr1 the value for mall_goods.attr1
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public void setAttr1(String attr1) {
        this.attr1 = attr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.attr2
     *
     * @return the value of mall_goods.attr2
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public String getAttr2() {
        return attr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.attr2
     *
     * @param attr2 the value for mall_goods.attr2
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public void setAttr2(String attr2) {
        this.attr2 = attr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.attr3
     *
     * @return the value of mall_goods.attr3
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public String getAttr3() {
        return attr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.attr3
     *
     * @param attr3 the value for mall_goods.attr3
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public void setAttr3(String attr3) {
        this.attr3 = attr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.test_item_list
     *
     * @return the value of mall_goods.test_item_list
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public String getTestItemList() {
        return testItemList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.test_item_list
     *
     * @param testItemList the value for mall_goods.test_item_list
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public void setTestItemList(String testItemList) {
        this.testItemList = testItemList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.meal_list
     *
     * @return the value of mall_goods.meal_list
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public String getMealList() {
        return mealList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.meal_list
     *
     * @param mealList the value for mall_goods.meal_list
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    public void setMealList(String mealList) {
        this.mealList = mealList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods
     *
     * @mbg.generated Thu Dec 29 10:38:21 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", goodsNum=").append(goodsNum);
        sb.append(", goodsName=").append(goodsName);
        sb.append(", price=").append(price);
        sb.append(", description=").append(description);
        sb.append(", hscode=").append(hscode);
        sb.append(", material=").append(material);
        sb.append(", export=").append(export);
        sb.append(", platform=").append(platform);
        sb.append(", standard=").append(standard);
        sb.append(", industClass=").append(industClass);
        sb.append(", busType=").append(busType);
        sb.append(", subtitle=").append(subtitle);
        sb.append(", attr1=").append(attr1);
        sb.append(", attr2=").append(attr2);
        sb.append(", attr3=").append(attr3);
        sb.append(", testItemList=").append(testItemList);
        sb.append(", mealList=").append(mealList);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}