package com.libiao.customer.dal.model;

import java.io.Serializable;

public class SystemParameter implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_parameter.param_key
     *
     * @mbg.generated Tue Dec 27 17:53:50 CST 2022
     */
    private String paramKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_parameter.param_value
     *
     * @mbg.generated Tue Dec 27 17:53:50 CST 2022
     */
    private String paramValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_parameter.param_desc
     *
     * @mbg.generated Tue Dec 27 17:53:50 CST 2022
     */
    private String paramDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_parameter
     *
     * @mbg.generated Tue Dec 27 17:53:50 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_parameter.param_key
     *
     * @return the value of system_parameter.param_key
     *
     * @mbg.generated Tue Dec 27 17:53:50 CST 2022
     */
    public String getParamKey() {
        return paramKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_parameter.param_key
     *
     * @param paramKey the value for system_parameter.param_key
     *
     * @mbg.generated Tue Dec 27 17:53:50 CST 2022
     */
    public void setParamKey(String paramKey) {
        this.paramKey = paramKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_parameter.param_value
     *
     * @return the value of system_parameter.param_value
     *
     * @mbg.generated Tue Dec 27 17:53:50 CST 2022
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_parameter.param_value
     *
     * @param paramValue the value for system_parameter.param_value
     *
     * @mbg.generated Tue Dec 27 17:53:50 CST 2022
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_parameter.param_desc
     *
     * @return the value of system_parameter.param_desc
     *
     * @mbg.generated Tue Dec 27 17:53:50 CST 2022
     */
    public String getParamDesc() {
        return paramDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_parameter.param_desc
     *
     * @param paramDesc the value for system_parameter.param_desc
     *
     * @mbg.generated Tue Dec 27 17:53:50 CST 2022
     */
    public void setParamDesc(String paramDesc) {
        this.paramDesc = paramDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated Tue Dec 27 17:53:50 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", paramKey=").append(paramKey);
        sb.append(", paramValue=").append(paramValue);
        sb.append(", paramDesc=").append(paramDesc);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}