package com.libiao.customer.dal.model;

import java.io.Serializable;
import java.util.Date;

public class TestQuotation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.id
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.client_id
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private Integer clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.client_name
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private String clientName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.user_id
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.user_org_no
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private String userOrgNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.state
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.step
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private Byte step;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.trade_name
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private String tradeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.quotation_num
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private String quotationNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.pay_status
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private Byte payStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.trade_desc
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private String tradeDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.pay_type
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private Byte payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.attn
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private String attn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.tel_client
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private String telClient;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.fax_client
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private String faxClient;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.email
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.gmt_create
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.invoice_title
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private String invoiceTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.delivery_address
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private String deliveryAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.bank_account_name
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private String bankAccountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.bank_account
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private String bankAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.bank_name
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.client_com_signature
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private String clientComSignature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.libiao_representative_signature
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private String libiaoRepresentativeSignature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.client_com_chop
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private String clientComChop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.audit
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private String audit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.client_signature_date
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private String clientSignatureDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.libiao_signature_date
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private String libiaoSignatureDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.test_trade_id
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private Long testTradeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.from_com
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private String fromCom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.report_fee
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private String reportFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.courier_fee
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private String courierFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.tax_fee
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private String taxFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.discount
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private String discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.total_cost
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private Integer totalCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.total_test_amt
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private Integer totalTestAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.paid_amt
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private Integer paidAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.service_id
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private Long serviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.type
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.orgQuotationNum
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private String orgquotationnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.audit_id
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private Long auditId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.audit_name
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private String auditName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.audit_reason
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private String auditReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation.remark
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_quotation
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.id
     *
     * @return the value of test_quotation.id
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.id
     *
     * @param id the value for test_quotation.id
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.client_id
     *
     * @return the value of test_quotation.client_id
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.client_id
     *
     * @param clientId the value for test_quotation.client_id
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.client_name
     *
     * @return the value of test_quotation.client_name
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.client_name
     *
     * @param clientName the value for test_quotation.client_name
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.user_id
     *
     * @return the value of test_quotation.user_id
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.user_id
     *
     * @param userId the value for test_quotation.user_id
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.user_org_no
     *
     * @return the value of test_quotation.user_org_no
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public String getUserOrgNo() {
        return userOrgNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.user_org_no
     *
     * @param userOrgNo the value for test_quotation.user_org_no
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setUserOrgNo(String userOrgNo) {
        this.userOrgNo = userOrgNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.state
     *
     * @return the value of test_quotation.state
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.state
     *
     * @param state the value for test_quotation.state
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.step
     *
     * @return the value of test_quotation.step
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public Byte getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.step
     *
     * @param step the value for test_quotation.step
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setStep(Byte step) {
        this.step = step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.trade_name
     *
     * @return the value of test_quotation.trade_name
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public String getTradeName() {
        return tradeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.trade_name
     *
     * @param tradeName the value for test_quotation.trade_name
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setTradeName(String tradeName) {
        this.tradeName = tradeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.quotation_num
     *
     * @return the value of test_quotation.quotation_num
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public String getQuotationNum() {
        return quotationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.quotation_num
     *
     * @param quotationNum the value for test_quotation.quotation_num
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setQuotationNum(String quotationNum) {
        this.quotationNum = quotationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.pay_status
     *
     * @return the value of test_quotation.pay_status
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public Byte getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.pay_status
     *
     * @param payStatus the value for test_quotation.pay_status
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setPayStatus(Byte payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.trade_desc
     *
     * @return the value of test_quotation.trade_desc
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public String getTradeDesc() {
        return tradeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.trade_desc
     *
     * @param tradeDesc the value for test_quotation.trade_desc
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setTradeDesc(String tradeDesc) {
        this.tradeDesc = tradeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.pay_type
     *
     * @return the value of test_quotation.pay_type
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public Byte getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.pay_type
     *
     * @param payType the value for test_quotation.pay_type
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setPayType(Byte payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.attn
     *
     * @return the value of test_quotation.attn
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public String getAttn() {
        return attn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.attn
     *
     * @param attn the value for test_quotation.attn
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setAttn(String attn) {
        this.attn = attn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.tel_client
     *
     * @return the value of test_quotation.tel_client
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public String getTelClient() {
        return telClient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.tel_client
     *
     * @param telClient the value for test_quotation.tel_client
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setTelClient(String telClient) {
        this.telClient = telClient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.fax_client
     *
     * @return the value of test_quotation.fax_client
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public String getFaxClient() {
        return faxClient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.fax_client
     *
     * @param faxClient the value for test_quotation.fax_client
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setFaxClient(String faxClient) {
        this.faxClient = faxClient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.email
     *
     * @return the value of test_quotation.email
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.email
     *
     * @param email the value for test_quotation.email
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.gmt_create
     *
     * @return the value of test_quotation.gmt_create
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.gmt_create
     *
     * @param gmtCreate the value for test_quotation.gmt_create
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.invoice_title
     *
     * @return the value of test_quotation.invoice_title
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public String getInvoiceTitle() {
        return invoiceTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.invoice_title
     *
     * @param invoiceTitle the value for test_quotation.invoice_title
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setInvoiceTitle(String invoiceTitle) {
        this.invoiceTitle = invoiceTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.delivery_address
     *
     * @return the value of test_quotation.delivery_address
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public String getDeliveryAddress() {
        return deliveryAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.delivery_address
     *
     * @param deliveryAddress the value for test_quotation.delivery_address
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setDeliveryAddress(String deliveryAddress) {
        this.deliveryAddress = deliveryAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.bank_account_name
     *
     * @return the value of test_quotation.bank_account_name
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public String getBankAccountName() {
        return bankAccountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.bank_account_name
     *
     * @param bankAccountName the value for test_quotation.bank_account_name
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setBankAccountName(String bankAccountName) {
        this.bankAccountName = bankAccountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.bank_account
     *
     * @return the value of test_quotation.bank_account
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.bank_account
     *
     * @param bankAccount the value for test_quotation.bank_account
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.bank_name
     *
     * @return the value of test_quotation.bank_name
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.bank_name
     *
     * @param bankName the value for test_quotation.bank_name
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.client_com_signature
     *
     * @return the value of test_quotation.client_com_signature
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public String getClientComSignature() {
        return clientComSignature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.client_com_signature
     *
     * @param clientComSignature the value for test_quotation.client_com_signature
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setClientComSignature(String clientComSignature) {
        this.clientComSignature = clientComSignature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.libiao_representative_signature
     *
     * @return the value of test_quotation.libiao_representative_signature
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public String getLibiaoRepresentativeSignature() {
        return libiaoRepresentativeSignature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.libiao_representative_signature
     *
     * @param libiaoRepresentativeSignature the value for test_quotation.libiao_representative_signature
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setLibiaoRepresentativeSignature(String libiaoRepresentativeSignature) {
        this.libiaoRepresentativeSignature = libiaoRepresentativeSignature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.client_com_chop
     *
     * @return the value of test_quotation.client_com_chop
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public String getClientComChop() {
        return clientComChop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.client_com_chop
     *
     * @param clientComChop the value for test_quotation.client_com_chop
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setClientComChop(String clientComChop) {
        this.clientComChop = clientComChop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.audit
     *
     * @return the value of test_quotation.audit
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public String getAudit() {
        return audit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.audit
     *
     * @param audit the value for test_quotation.audit
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setAudit(String audit) {
        this.audit = audit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.client_signature_date
     *
     * @return the value of test_quotation.client_signature_date
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public String getClientSignatureDate() {
        return clientSignatureDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.client_signature_date
     *
     * @param clientSignatureDate the value for test_quotation.client_signature_date
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setClientSignatureDate(String clientSignatureDate) {
        this.clientSignatureDate = clientSignatureDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.libiao_signature_date
     *
     * @return the value of test_quotation.libiao_signature_date
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public String getLibiaoSignatureDate() {
        return libiaoSignatureDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.libiao_signature_date
     *
     * @param libiaoSignatureDate the value for test_quotation.libiao_signature_date
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setLibiaoSignatureDate(String libiaoSignatureDate) {
        this.libiaoSignatureDate = libiaoSignatureDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.test_trade_id
     *
     * @return the value of test_quotation.test_trade_id
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public Long getTestTradeId() {
        return testTradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.test_trade_id
     *
     * @param testTradeId the value for test_quotation.test_trade_id
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setTestTradeId(Long testTradeId) {
        this.testTradeId = testTradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.from_com
     *
     * @return the value of test_quotation.from_com
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public String getFromCom() {
        return fromCom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.from_com
     *
     * @param fromCom the value for test_quotation.from_com
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setFromCom(String fromCom) {
        this.fromCom = fromCom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.report_fee
     *
     * @return the value of test_quotation.report_fee
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public String getReportFee() {
        return reportFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.report_fee
     *
     * @param reportFee the value for test_quotation.report_fee
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setReportFee(String reportFee) {
        this.reportFee = reportFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.courier_fee
     *
     * @return the value of test_quotation.courier_fee
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public String getCourierFee() {
        return courierFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.courier_fee
     *
     * @param courierFee the value for test_quotation.courier_fee
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setCourierFee(String courierFee) {
        this.courierFee = courierFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.tax_fee
     *
     * @return the value of test_quotation.tax_fee
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public String getTaxFee() {
        return taxFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.tax_fee
     *
     * @param taxFee the value for test_quotation.tax_fee
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setTaxFee(String taxFee) {
        this.taxFee = taxFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.discount
     *
     * @return the value of test_quotation.discount
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public String getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.discount
     *
     * @param discount the value for test_quotation.discount
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setDiscount(String discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.total_cost
     *
     * @return the value of test_quotation.total_cost
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public Integer getTotalCost() {
        return totalCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.total_cost
     *
     * @param totalCost the value for test_quotation.total_cost
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setTotalCost(Integer totalCost) {
        this.totalCost = totalCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.total_test_amt
     *
     * @return the value of test_quotation.total_test_amt
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public Integer getTotalTestAmt() {
        return totalTestAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.total_test_amt
     *
     * @param totalTestAmt the value for test_quotation.total_test_amt
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setTotalTestAmt(Integer totalTestAmt) {
        this.totalTestAmt = totalTestAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.paid_amt
     *
     * @return the value of test_quotation.paid_amt
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public Integer getPaidAmt() {
        return paidAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.paid_amt
     *
     * @param paidAmt the value for test_quotation.paid_amt
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setPaidAmt(Integer paidAmt) {
        this.paidAmt = paidAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.service_id
     *
     * @return the value of test_quotation.service_id
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public Long getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.service_id
     *
     * @param serviceId the value for test_quotation.service_id
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setServiceId(Long serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.type
     *
     * @return the value of test_quotation.type
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.type
     *
     * @param type the value for test_quotation.type
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.orgQuotationNum
     *
     * @return the value of test_quotation.orgQuotationNum
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public String getOrgquotationnum() {
        return orgquotationnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.orgQuotationNum
     *
     * @param orgquotationnum the value for test_quotation.orgQuotationNum
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setOrgquotationnum(String orgquotationnum) {
        this.orgquotationnum = orgquotationnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.audit_id
     *
     * @return the value of test_quotation.audit_id
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public Long getAuditId() {
        return auditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.audit_id
     *
     * @param auditId the value for test_quotation.audit_id
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setAuditId(Long auditId) {
        this.auditId = auditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.audit_name
     *
     * @return the value of test_quotation.audit_name
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public String getAuditName() {
        return auditName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.audit_name
     *
     * @param auditName the value for test_quotation.audit_name
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setAuditName(String auditName) {
        this.auditName = auditName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.audit_reason
     *
     * @return the value of test_quotation.audit_reason
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public String getAuditReason() {
        return auditReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.audit_reason
     *
     * @param auditReason the value for test_quotation.audit_reason
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setAuditReason(String auditReason) {
        this.auditReason = auditReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation.remark
     *
     * @return the value of test_quotation.remark
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation.remark
     *
     * @param remark the value for test_quotation.remark
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation
     *
     * @mbg.generated Wed Dec 28 10:55:30 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", clientId=").append(clientId);
        sb.append(", clientName=").append(clientName);
        sb.append(", userId=").append(userId);
        sb.append(", userOrgNo=").append(userOrgNo);
        sb.append(", state=").append(state);
        sb.append(", step=").append(step);
        sb.append(", tradeName=").append(tradeName);
        sb.append(", quotationNum=").append(quotationNum);
        sb.append(", payStatus=").append(payStatus);
        sb.append(", tradeDesc=").append(tradeDesc);
        sb.append(", payType=").append(payType);
        sb.append(", attn=").append(attn);
        sb.append(", telClient=").append(telClient);
        sb.append(", faxClient=").append(faxClient);
        sb.append(", email=").append(email);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", invoiceTitle=").append(invoiceTitle);
        sb.append(", deliveryAddress=").append(deliveryAddress);
        sb.append(", bankAccountName=").append(bankAccountName);
        sb.append(", bankAccount=").append(bankAccount);
        sb.append(", bankName=").append(bankName);
        sb.append(", clientComSignature=").append(clientComSignature);
        sb.append(", libiaoRepresentativeSignature=").append(libiaoRepresentativeSignature);
        sb.append(", clientComChop=").append(clientComChop);
        sb.append(", audit=").append(audit);
        sb.append(", clientSignatureDate=").append(clientSignatureDate);
        sb.append(", libiaoSignatureDate=").append(libiaoSignatureDate);
        sb.append(", testTradeId=").append(testTradeId);
        sb.append(", fromCom=").append(fromCom);
        sb.append(", reportFee=").append(reportFee);
        sb.append(", courierFee=").append(courierFee);
        sb.append(", taxFee=").append(taxFee);
        sb.append(", discount=").append(discount);
        sb.append(", totalCost=").append(totalCost);
        sb.append(", totalTestAmt=").append(totalTestAmt);
        sb.append(", paidAmt=").append(paidAmt);
        sb.append(", serviceId=").append(serviceId);
        sb.append(", type=").append(type);
        sb.append(", orgquotationnum=").append(orgquotationnum);
        sb.append(", auditId=").append(auditId);
        sb.append(", auditName=").append(auditName);
        sb.append(", auditReason=").append(auditReason);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}