package com.libiao.customer.dal.model;

import java.io.Serializable;

public class TestQuotationItem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation_item.id
     *
     * @mbg.generated Wed Dec 28 10:06:12 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation_item.test_quotation_num
     *
     * @mbg.generated Wed Dec 28 10:06:12 CST 2022
     */
    private String testQuotationNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation_item.test_quotation_goods_id
     *
     * @mbg.generated Wed Dec 28 10:06:12 CST 2022
     */
    private Long testQuotationGoodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation_item.test_item
     *
     * @mbg.generated Wed Dec 28 10:06:12 CST 2022
     */
    private String testItem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation_item.unit_price
     *
     * @mbg.generated Wed Dec 28 10:06:12 CST 2022
     */
    private Integer unitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation_item.quantity
     *
     * @mbg.generated Wed Dec 28 10:06:12 CST 2022
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation_item.amount_rmb
     *
     * @mbg.generated Wed Dec 28 10:06:12 CST 2022
     */
    private Integer amountRmb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation_item.sample_qty
     *
     * @mbg.generated Wed Dec 28 10:06:12 CST 2022
     */
    private Integer sampleQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_quotation_item
     *
     * @mbg.generated Wed Dec 28 10:06:12 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation_item.id
     *
     * @return the value of test_quotation_item.id
     *
     * @mbg.generated Wed Dec 28 10:06:12 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation_item.id
     *
     * @param id the value for test_quotation_item.id
     *
     * @mbg.generated Wed Dec 28 10:06:12 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation_item.test_quotation_num
     *
     * @return the value of test_quotation_item.test_quotation_num
     *
     * @mbg.generated Wed Dec 28 10:06:12 CST 2022
     */
    public String getTestQuotationNum() {
        return testQuotationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation_item.test_quotation_num
     *
     * @param testQuotationNum the value for test_quotation_item.test_quotation_num
     *
     * @mbg.generated Wed Dec 28 10:06:12 CST 2022
     */
    public void setTestQuotationNum(String testQuotationNum) {
        this.testQuotationNum = testQuotationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation_item.test_quotation_goods_id
     *
     * @return the value of test_quotation_item.test_quotation_goods_id
     *
     * @mbg.generated Wed Dec 28 10:06:12 CST 2022
     */
    public Long getTestQuotationGoodsId() {
        return testQuotationGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation_item.test_quotation_goods_id
     *
     * @param testQuotationGoodsId the value for test_quotation_item.test_quotation_goods_id
     *
     * @mbg.generated Wed Dec 28 10:06:12 CST 2022
     */
    public void setTestQuotationGoodsId(Long testQuotationGoodsId) {
        this.testQuotationGoodsId = testQuotationGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation_item.test_item
     *
     * @return the value of test_quotation_item.test_item
     *
     * @mbg.generated Wed Dec 28 10:06:12 CST 2022
     */
    public String getTestItem() {
        return testItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation_item.test_item
     *
     * @param testItem the value for test_quotation_item.test_item
     *
     * @mbg.generated Wed Dec 28 10:06:12 CST 2022
     */
    public void setTestItem(String testItem) {
        this.testItem = testItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation_item.unit_price
     *
     * @return the value of test_quotation_item.unit_price
     *
     * @mbg.generated Wed Dec 28 10:06:12 CST 2022
     */
    public Integer getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation_item.unit_price
     *
     * @param unitPrice the value for test_quotation_item.unit_price
     *
     * @mbg.generated Wed Dec 28 10:06:12 CST 2022
     */
    public void setUnitPrice(Integer unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation_item.quantity
     *
     * @return the value of test_quotation_item.quantity
     *
     * @mbg.generated Wed Dec 28 10:06:12 CST 2022
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation_item.quantity
     *
     * @param quantity the value for test_quotation_item.quantity
     *
     * @mbg.generated Wed Dec 28 10:06:12 CST 2022
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation_item.amount_rmb
     *
     * @return the value of test_quotation_item.amount_rmb
     *
     * @mbg.generated Wed Dec 28 10:06:12 CST 2022
     */
    public Integer getAmountRmb() {
        return amountRmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation_item.amount_rmb
     *
     * @param amountRmb the value for test_quotation_item.amount_rmb
     *
     * @mbg.generated Wed Dec 28 10:06:12 CST 2022
     */
    public void setAmountRmb(Integer amountRmb) {
        this.amountRmb = amountRmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation_item.sample_qty
     *
     * @return the value of test_quotation_item.sample_qty
     *
     * @mbg.generated Wed Dec 28 10:06:12 CST 2022
     */
    public Integer getSampleQty() {
        return sampleQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation_item.sample_qty
     *
     * @param sampleQty the value for test_quotation_item.sample_qty
     *
     * @mbg.generated Wed Dec 28 10:06:12 CST 2022
     */
    public void setSampleQty(Integer sampleQty) {
        this.sampleQty = sampleQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_item
     *
     * @mbg.generated Wed Dec 28 10:06:12 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", testQuotationNum=").append(testQuotationNum);
        sb.append(", testQuotationGoodsId=").append(testQuotationGoodsId);
        sb.append(", testItem=").append(testItem);
        sb.append(", unitPrice=").append(unitPrice);
        sb.append(", quantity=").append(quantity);
        sb.append(", amountRmb=").append(amountRmb);
        sb.append(", sampleQty=").append(sampleQty);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}