package com.libiao.customer.dal.model;

import java.util.ArrayList;
import java.util.List;

public class TestApplicationSampleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_application_sample
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_application_sample
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_application_sample
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_sample
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    public TestApplicationSampleExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_sample
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_sample
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_sample
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_sample
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_sample
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_sample
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_sample
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_sample
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_sample
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_sample
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_application_sample
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andApplicationFormIdIsNull() {
            addCriterion("application_form_id is null");
            return (Criteria) this;
        }

        public Criteria andApplicationFormIdIsNotNull() {
            addCriterion("application_form_id is not null");
            return (Criteria) this;
        }

        public Criteria andApplicationFormIdEqualTo(Long value) {
            addCriterion("application_form_id =", value, "applicationFormId");
            return (Criteria) this;
        }

        public Criteria andApplicationFormIdNotEqualTo(Long value) {
            addCriterion("application_form_id <>", value, "applicationFormId");
            return (Criteria) this;
        }

        public Criteria andApplicationFormIdGreaterThan(Long value) {
            addCriterion("application_form_id >", value, "applicationFormId");
            return (Criteria) this;
        }

        public Criteria andApplicationFormIdGreaterThanOrEqualTo(Long value) {
            addCriterion("application_form_id >=", value, "applicationFormId");
            return (Criteria) this;
        }

        public Criteria andApplicationFormIdLessThan(Long value) {
            addCriterion("application_form_id <", value, "applicationFormId");
            return (Criteria) this;
        }

        public Criteria andApplicationFormIdLessThanOrEqualTo(Long value) {
            addCriterion("application_form_id <=", value, "applicationFormId");
            return (Criteria) this;
        }

        public Criteria andApplicationFormIdIn(List<Long> values) {
            addCriterion("application_form_id in", values, "applicationFormId");
            return (Criteria) this;
        }

        public Criteria andApplicationFormIdNotIn(List<Long> values) {
            addCriterion("application_form_id not in", values, "applicationFormId");
            return (Criteria) this;
        }

        public Criteria andApplicationFormIdBetween(Long value1, Long value2) {
            addCriterion("application_form_id between", value1, value2, "applicationFormId");
            return (Criteria) this;
        }

        public Criteria andApplicationFormIdNotBetween(Long value1, Long value2) {
            addCriterion("application_form_id not between", value1, value2, "applicationFormId");
            return (Criteria) this;
        }

        public Criteria andApplicationNumIsNull() {
            addCriterion("application_num is null");
            return (Criteria) this;
        }

        public Criteria andApplicationNumIsNotNull() {
            addCriterion("application_num is not null");
            return (Criteria) this;
        }

        public Criteria andApplicationNumEqualTo(String value) {
            addCriterion("application_num =", value, "applicationNum");
            return (Criteria) this;
        }

        public Criteria andApplicationNumNotEqualTo(String value) {
            addCriterion("application_num <>", value, "applicationNum");
            return (Criteria) this;
        }

        public Criteria andApplicationNumGreaterThan(String value) {
            addCriterion("application_num >", value, "applicationNum");
            return (Criteria) this;
        }

        public Criteria andApplicationNumGreaterThanOrEqualTo(String value) {
            addCriterion("application_num >=", value, "applicationNum");
            return (Criteria) this;
        }

        public Criteria andApplicationNumLessThan(String value) {
            addCriterion("application_num <", value, "applicationNum");
            return (Criteria) this;
        }

        public Criteria andApplicationNumLessThanOrEqualTo(String value) {
            addCriterion("application_num <=", value, "applicationNum");
            return (Criteria) this;
        }

        public Criteria andApplicationNumLike(String value) {
            addCriterion("application_num like", value, "applicationNum");
            return (Criteria) this;
        }

        public Criteria andApplicationNumNotLike(String value) {
            addCriterion("application_num not like", value, "applicationNum");
            return (Criteria) this;
        }

        public Criteria andApplicationNumIn(List<String> values) {
            addCriterion("application_num in", values, "applicationNum");
            return (Criteria) this;
        }

        public Criteria andApplicationNumNotIn(List<String> values) {
            addCriterion("application_num not in", values, "applicationNum");
            return (Criteria) this;
        }

        public Criteria andApplicationNumBetween(String value1, String value2) {
            addCriterion("application_num between", value1, value2, "applicationNum");
            return (Criteria) this;
        }

        public Criteria andApplicationNumNotBetween(String value1, String value2) {
            addCriterion("application_num not between", value1, value2, "applicationNum");
            return (Criteria) this;
        }

        public Criteria andSampleNameIsNull() {
            addCriterion("sample_name is null");
            return (Criteria) this;
        }

        public Criteria andSampleNameIsNotNull() {
            addCriterion("sample_name is not null");
            return (Criteria) this;
        }

        public Criteria andSampleNameEqualTo(String value) {
            addCriterion("sample_name =", value, "sampleName");
            return (Criteria) this;
        }

        public Criteria andSampleNameNotEqualTo(String value) {
            addCriterion("sample_name <>", value, "sampleName");
            return (Criteria) this;
        }

        public Criteria andSampleNameGreaterThan(String value) {
            addCriterion("sample_name >", value, "sampleName");
            return (Criteria) this;
        }

        public Criteria andSampleNameGreaterThanOrEqualTo(String value) {
            addCriterion("sample_name >=", value, "sampleName");
            return (Criteria) this;
        }

        public Criteria andSampleNameLessThan(String value) {
            addCriterion("sample_name <", value, "sampleName");
            return (Criteria) this;
        }

        public Criteria andSampleNameLessThanOrEqualTo(String value) {
            addCriterion("sample_name <=", value, "sampleName");
            return (Criteria) this;
        }

        public Criteria andSampleNameLike(String value) {
            addCriterion("sample_name like", value, "sampleName");
            return (Criteria) this;
        }

        public Criteria andSampleNameNotLike(String value) {
            addCriterion("sample_name not like", value, "sampleName");
            return (Criteria) this;
        }

        public Criteria andSampleNameIn(List<String> values) {
            addCriterion("sample_name in", values, "sampleName");
            return (Criteria) this;
        }

        public Criteria andSampleNameNotIn(List<String> values) {
            addCriterion("sample_name not in", values, "sampleName");
            return (Criteria) this;
        }

        public Criteria andSampleNameBetween(String value1, String value2) {
            addCriterion("sample_name between", value1, value2, "sampleName");
            return (Criteria) this;
        }

        public Criteria andSampleNameNotBetween(String value1, String value2) {
            addCriterion("sample_name not between", value1, value2, "sampleName");
            return (Criteria) this;
        }

        public Criteria andSampleModelIsNull() {
            addCriterion("sample_model is null");
            return (Criteria) this;
        }

        public Criteria andSampleModelIsNotNull() {
            addCriterion("sample_model is not null");
            return (Criteria) this;
        }

        public Criteria andSampleModelEqualTo(String value) {
            addCriterion("sample_model =", value, "sampleModel");
            return (Criteria) this;
        }

        public Criteria andSampleModelNotEqualTo(String value) {
            addCriterion("sample_model <>", value, "sampleModel");
            return (Criteria) this;
        }

        public Criteria andSampleModelGreaterThan(String value) {
            addCriterion("sample_model >", value, "sampleModel");
            return (Criteria) this;
        }

        public Criteria andSampleModelGreaterThanOrEqualTo(String value) {
            addCriterion("sample_model >=", value, "sampleModel");
            return (Criteria) this;
        }

        public Criteria andSampleModelLessThan(String value) {
            addCriterion("sample_model <", value, "sampleModel");
            return (Criteria) this;
        }

        public Criteria andSampleModelLessThanOrEqualTo(String value) {
            addCriterion("sample_model <=", value, "sampleModel");
            return (Criteria) this;
        }

        public Criteria andSampleModelLike(String value) {
            addCriterion("sample_model like", value, "sampleModel");
            return (Criteria) this;
        }

        public Criteria andSampleModelNotLike(String value) {
            addCriterion("sample_model not like", value, "sampleModel");
            return (Criteria) this;
        }

        public Criteria andSampleModelIn(List<String> values) {
            addCriterion("sample_model in", values, "sampleModel");
            return (Criteria) this;
        }

        public Criteria andSampleModelNotIn(List<String> values) {
            addCriterion("sample_model not in", values, "sampleModel");
            return (Criteria) this;
        }

        public Criteria andSampleModelBetween(String value1, String value2) {
            addCriterion("sample_model between", value1, value2, "sampleModel");
            return (Criteria) this;
        }

        public Criteria andSampleModelNotBetween(String value1, String value2) {
            addCriterion("sample_model not between", value1, value2, "sampleModel");
            return (Criteria) this;
        }

        public Criteria andSampleMaterialIsNull() {
            addCriterion("sample_material is null");
            return (Criteria) this;
        }

        public Criteria andSampleMaterialIsNotNull() {
            addCriterion("sample_material is not null");
            return (Criteria) this;
        }

        public Criteria andSampleMaterialEqualTo(String value) {
            addCriterion("sample_material =", value, "sampleMaterial");
            return (Criteria) this;
        }

        public Criteria andSampleMaterialNotEqualTo(String value) {
            addCriterion("sample_material <>", value, "sampleMaterial");
            return (Criteria) this;
        }

        public Criteria andSampleMaterialGreaterThan(String value) {
            addCriterion("sample_material >", value, "sampleMaterial");
            return (Criteria) this;
        }

        public Criteria andSampleMaterialGreaterThanOrEqualTo(String value) {
            addCriterion("sample_material >=", value, "sampleMaterial");
            return (Criteria) this;
        }

        public Criteria andSampleMaterialLessThan(String value) {
            addCriterion("sample_material <", value, "sampleMaterial");
            return (Criteria) this;
        }

        public Criteria andSampleMaterialLessThanOrEqualTo(String value) {
            addCriterion("sample_material <=", value, "sampleMaterial");
            return (Criteria) this;
        }

        public Criteria andSampleMaterialLike(String value) {
            addCriterion("sample_material like", value, "sampleMaterial");
            return (Criteria) this;
        }

        public Criteria andSampleMaterialNotLike(String value) {
            addCriterion("sample_material not like", value, "sampleMaterial");
            return (Criteria) this;
        }

        public Criteria andSampleMaterialIn(List<String> values) {
            addCriterion("sample_material in", values, "sampleMaterial");
            return (Criteria) this;
        }

        public Criteria andSampleMaterialNotIn(List<String> values) {
            addCriterion("sample_material not in", values, "sampleMaterial");
            return (Criteria) this;
        }

        public Criteria andSampleMaterialBetween(String value1, String value2) {
            addCriterion("sample_material between", value1, value2, "sampleMaterial");
            return (Criteria) this;
        }

        public Criteria andSampleMaterialNotBetween(String value1, String value2) {
            addCriterion("sample_material not between", value1, value2, "sampleMaterial");
            return (Criteria) this;
        }

        public Criteria andSampleDescriptionIsNull() {
            addCriterion("sample_description is null");
            return (Criteria) this;
        }

        public Criteria andSampleDescriptionIsNotNull() {
            addCriterion("sample_description is not null");
            return (Criteria) this;
        }

        public Criteria andSampleDescriptionEqualTo(String value) {
            addCriterion("sample_description =", value, "sampleDescription");
            return (Criteria) this;
        }

        public Criteria andSampleDescriptionNotEqualTo(String value) {
            addCriterion("sample_description <>", value, "sampleDescription");
            return (Criteria) this;
        }

        public Criteria andSampleDescriptionGreaterThan(String value) {
            addCriterion("sample_description >", value, "sampleDescription");
            return (Criteria) this;
        }

        public Criteria andSampleDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("sample_description >=", value, "sampleDescription");
            return (Criteria) this;
        }

        public Criteria andSampleDescriptionLessThan(String value) {
            addCriterion("sample_description <", value, "sampleDescription");
            return (Criteria) this;
        }

        public Criteria andSampleDescriptionLessThanOrEqualTo(String value) {
            addCriterion("sample_description <=", value, "sampleDescription");
            return (Criteria) this;
        }

        public Criteria andSampleDescriptionLike(String value) {
            addCriterion("sample_description like", value, "sampleDescription");
            return (Criteria) this;
        }

        public Criteria andSampleDescriptionNotLike(String value) {
            addCriterion("sample_description not like", value, "sampleDescription");
            return (Criteria) this;
        }

        public Criteria andSampleDescriptionIn(List<String> values) {
            addCriterion("sample_description in", values, "sampleDescription");
            return (Criteria) this;
        }

        public Criteria andSampleDescriptionNotIn(List<String> values) {
            addCriterion("sample_description not in", values, "sampleDescription");
            return (Criteria) this;
        }

        public Criteria andSampleDescriptionBetween(String value1, String value2) {
            addCriterion("sample_description between", value1, value2, "sampleDescription");
            return (Criteria) this;
        }

        public Criteria andSampleDescriptionNotBetween(String value1, String value2) {
            addCriterion("sample_description not between", value1, value2, "sampleDescription");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_application_sample
     *
     * @mbg.generated do_not_delete_during_merge Sun Jan 01 14:43:46 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_application_sample
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}