package com.libiao.customer.dal.model;

import java.util.ArrayList;
import java.util.List;

public class TestQuotationItemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_quotation_item
     *
     * @mbg.generated Tue Dec 27 16:19:50 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_quotation_item
     *
     * @mbg.generated Tue Dec 27 16:19:50 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_quotation_item
     *
     * @mbg.generated Tue Dec 27 16:19:50 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_item
     *
     * @mbg.generated Tue Dec 27 16:19:50 CST 2022
     */
    public TestQuotationItemExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_item
     *
     * @mbg.generated Tue Dec 27 16:19:50 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_item
     *
     * @mbg.generated Tue Dec 27 16:19:50 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_item
     *
     * @mbg.generated Tue Dec 27 16:19:50 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_item
     *
     * @mbg.generated Tue Dec 27 16:19:50 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_item
     *
     * @mbg.generated Tue Dec 27 16:19:50 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_item
     *
     * @mbg.generated Tue Dec 27 16:19:50 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_item
     *
     * @mbg.generated Tue Dec 27 16:19:50 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_item
     *
     * @mbg.generated Tue Dec 27 16:19:50 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_item
     *
     * @mbg.generated Tue Dec 27 16:19:50 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_item
     *
     * @mbg.generated Tue Dec 27 16:19:50 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_quotation_item
     *
     * @mbg.generated Tue Dec 27 16:19:50 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTestQuotationIdIsNull() {
            addCriterion("test_quotation_id is null");
            return (Criteria) this;
        }

        public Criteria andTestQuotationIdIsNotNull() {
            addCriterion("test_quotation_id is not null");
            return (Criteria) this;
        }

        public Criteria andTestQuotationIdEqualTo(Long value) {
            addCriterion("test_quotation_id =", value, "testQuotationId");
            return (Criteria) this;
        }

        public Criteria andTestQuotationIdNotEqualTo(Long value) {
            addCriterion("test_quotation_id <>", value, "testQuotationId");
            return (Criteria) this;
        }

        public Criteria andTestQuotationIdGreaterThan(Long value) {
            addCriterion("test_quotation_id >", value, "testQuotationId");
            return (Criteria) this;
        }

        public Criteria andTestQuotationIdGreaterThanOrEqualTo(Long value) {
            addCriterion("test_quotation_id >=", value, "testQuotationId");
            return (Criteria) this;
        }

        public Criteria andTestQuotationIdLessThan(Long value) {
            addCriterion("test_quotation_id <", value, "testQuotationId");
            return (Criteria) this;
        }

        public Criteria andTestQuotationIdLessThanOrEqualTo(Long value) {
            addCriterion("test_quotation_id <=", value, "testQuotationId");
            return (Criteria) this;
        }

        public Criteria andTestQuotationIdIn(List<Long> values) {
            addCriterion("test_quotation_id in", values, "testQuotationId");
            return (Criteria) this;
        }

        public Criteria andTestQuotationIdNotIn(List<Long> values) {
            addCriterion("test_quotation_id not in", values, "testQuotationId");
            return (Criteria) this;
        }

        public Criteria andTestQuotationIdBetween(Long value1, Long value2) {
            addCriterion("test_quotation_id between", value1, value2, "testQuotationId");
            return (Criteria) this;
        }

        public Criteria andTestQuotationIdNotBetween(Long value1, Long value2) {
            addCriterion("test_quotation_id not between", value1, value2, "testQuotationId");
            return (Criteria) this;
        }

        public Criteria andTestQuotationGoodsIdIsNull() {
            addCriterion("test_quotation_goods_id is null");
            return (Criteria) this;
        }

        public Criteria andTestQuotationGoodsIdIsNotNull() {
            addCriterion("test_quotation_goods_id is not null");
            return (Criteria) this;
        }

        public Criteria andTestQuotationGoodsIdEqualTo(Long value) {
            addCriterion("test_quotation_goods_id =", value, "testQuotationGoodsId");
            return (Criteria) this;
        }

        public Criteria andTestQuotationGoodsIdNotEqualTo(Long value) {
            addCriterion("test_quotation_goods_id <>", value, "testQuotationGoodsId");
            return (Criteria) this;
        }

        public Criteria andTestQuotationGoodsIdGreaterThan(Long value) {
            addCriterion("test_quotation_goods_id >", value, "testQuotationGoodsId");
            return (Criteria) this;
        }

        public Criteria andTestQuotationGoodsIdGreaterThanOrEqualTo(Long value) {
            addCriterion("test_quotation_goods_id >=", value, "testQuotationGoodsId");
            return (Criteria) this;
        }

        public Criteria andTestQuotationGoodsIdLessThan(Long value) {
            addCriterion("test_quotation_goods_id <", value, "testQuotationGoodsId");
            return (Criteria) this;
        }

        public Criteria andTestQuotationGoodsIdLessThanOrEqualTo(Long value) {
            addCriterion("test_quotation_goods_id <=", value, "testQuotationGoodsId");
            return (Criteria) this;
        }

        public Criteria andTestQuotationGoodsIdIn(List<Long> values) {
            addCriterion("test_quotation_goods_id in", values, "testQuotationGoodsId");
            return (Criteria) this;
        }

        public Criteria andTestQuotationGoodsIdNotIn(List<Long> values) {
            addCriterion("test_quotation_goods_id not in", values, "testQuotationGoodsId");
            return (Criteria) this;
        }

        public Criteria andTestQuotationGoodsIdBetween(Long value1, Long value2) {
            addCriterion("test_quotation_goods_id between", value1, value2, "testQuotationGoodsId");
            return (Criteria) this;
        }

        public Criteria andTestQuotationGoodsIdNotBetween(Long value1, Long value2) {
            addCriterion("test_quotation_goods_id not between", value1, value2, "testQuotationGoodsId");
            return (Criteria) this;
        }

        public Criteria andReportNumIsNull() {
            addCriterion("report_num is null");
            return (Criteria) this;
        }

        public Criteria andReportNumIsNotNull() {
            addCriterion("report_num is not null");
            return (Criteria) this;
        }

        public Criteria andReportNumEqualTo(String value) {
            addCriterion("report_num =", value, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumNotEqualTo(String value) {
            addCriterion("report_num <>", value, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumGreaterThan(String value) {
            addCriterion("report_num >", value, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumGreaterThanOrEqualTo(String value) {
            addCriterion("report_num >=", value, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumLessThan(String value) {
            addCriterion("report_num <", value, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumLessThanOrEqualTo(String value) {
            addCriterion("report_num <=", value, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumLike(String value) {
            addCriterion("report_num like", value, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumNotLike(String value) {
            addCriterion("report_num not like", value, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumIn(List<String> values) {
            addCriterion("report_num in", values, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumNotIn(List<String> values) {
            addCriterion("report_num not in", values, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumBetween(String value1, String value2) {
            addCriterion("report_num between", value1, value2, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumNotBetween(String value1, String value2) {
            addCriterion("report_num not between", value1, value2, "reportNum");
            return (Criteria) this;
        }

        public Criteria andProductDesIsNull() {
            addCriterion("product_des is null");
            return (Criteria) this;
        }

        public Criteria andProductDesIsNotNull() {
            addCriterion("product_des is not null");
            return (Criteria) this;
        }

        public Criteria andProductDesEqualTo(String value) {
            addCriterion("product_des =", value, "productDes");
            return (Criteria) this;
        }

        public Criteria andProductDesNotEqualTo(String value) {
            addCriterion("product_des <>", value, "productDes");
            return (Criteria) this;
        }

        public Criteria andProductDesGreaterThan(String value) {
            addCriterion("product_des >", value, "productDes");
            return (Criteria) this;
        }

        public Criteria andProductDesGreaterThanOrEqualTo(String value) {
            addCriterion("product_des >=", value, "productDes");
            return (Criteria) this;
        }

        public Criteria andProductDesLessThan(String value) {
            addCriterion("product_des <", value, "productDes");
            return (Criteria) this;
        }

        public Criteria andProductDesLessThanOrEqualTo(String value) {
            addCriterion("product_des <=", value, "productDes");
            return (Criteria) this;
        }

        public Criteria andProductDesLike(String value) {
            addCriterion("product_des like", value, "productDes");
            return (Criteria) this;
        }

        public Criteria andProductDesNotLike(String value) {
            addCriterion("product_des not like", value, "productDes");
            return (Criteria) this;
        }

        public Criteria andProductDesIn(List<String> values) {
            addCriterion("product_des in", values, "productDes");
            return (Criteria) this;
        }

        public Criteria andProductDesNotIn(List<String> values) {
            addCriterion("product_des not in", values, "productDes");
            return (Criteria) this;
        }

        public Criteria andProductDesBetween(String value1, String value2) {
            addCriterion("product_des between", value1, value2, "productDes");
            return (Criteria) this;
        }

        public Criteria andProductDesNotBetween(String value1, String value2) {
            addCriterion("product_des not between", value1, value2, "productDes");
            return (Criteria) this;
        }

        public Criteria andStyleIsNull() {
            addCriterion("style is null");
            return (Criteria) this;
        }

        public Criteria andStyleIsNotNull() {
            addCriterion("style is not null");
            return (Criteria) this;
        }

        public Criteria andStyleEqualTo(String value) {
            addCriterion("style =", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleNotEqualTo(String value) {
            addCriterion("style <>", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleGreaterThan(String value) {
            addCriterion("style >", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleGreaterThanOrEqualTo(String value) {
            addCriterion("style >=", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleLessThan(String value) {
            addCriterion("style <", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleLessThanOrEqualTo(String value) {
            addCriterion("style <=", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleLike(String value) {
            addCriterion("style like", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleNotLike(String value) {
            addCriterion("style not like", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleIn(List<String> values) {
            addCriterion("style in", values, "style");
            return (Criteria) this;
        }

        public Criteria andStyleNotIn(List<String> values) {
            addCriterion("style not in", values, "style");
            return (Criteria) this;
        }

        public Criteria andStyleBetween(String value1, String value2) {
            addCriterion("style between", value1, value2, "style");
            return (Criteria) this;
        }

        public Criteria andStyleNotBetween(String value1, String value2) {
            addCriterion("style not between", value1, value2, "style");
            return (Criteria) this;
        }

        public Criteria andMaterialColorIsNull() {
            addCriterion("material_color is null");
            return (Criteria) this;
        }

        public Criteria andMaterialColorIsNotNull() {
            addCriterion("material_color is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialColorEqualTo(String value) {
            addCriterion("material_color =", value, "materialColor");
            return (Criteria) this;
        }

        public Criteria andMaterialColorNotEqualTo(String value) {
            addCriterion("material_color <>", value, "materialColor");
            return (Criteria) this;
        }

        public Criteria andMaterialColorGreaterThan(String value) {
            addCriterion("material_color >", value, "materialColor");
            return (Criteria) this;
        }

        public Criteria andMaterialColorGreaterThanOrEqualTo(String value) {
            addCriterion("material_color >=", value, "materialColor");
            return (Criteria) this;
        }

        public Criteria andMaterialColorLessThan(String value) {
            addCriterion("material_color <", value, "materialColor");
            return (Criteria) this;
        }

        public Criteria andMaterialColorLessThanOrEqualTo(String value) {
            addCriterion("material_color <=", value, "materialColor");
            return (Criteria) this;
        }

        public Criteria andMaterialColorLike(String value) {
            addCriterion("material_color like", value, "materialColor");
            return (Criteria) this;
        }

        public Criteria andMaterialColorNotLike(String value) {
            addCriterion("material_color not like", value, "materialColor");
            return (Criteria) this;
        }

        public Criteria andMaterialColorIn(List<String> values) {
            addCriterion("material_color in", values, "materialColor");
            return (Criteria) this;
        }

        public Criteria andMaterialColorNotIn(List<String> values) {
            addCriterion("material_color not in", values, "materialColor");
            return (Criteria) this;
        }

        public Criteria andMaterialColorBetween(String value1, String value2) {
            addCriterion("material_color between", value1, value2, "materialColor");
            return (Criteria) this;
        }

        public Criteria andMaterialColorNotBetween(String value1, String value2) {
            addCriterion("material_color not between", value1, value2, "materialColor");
            return (Criteria) this;
        }

        public Criteria andTestItemIsNull() {
            addCriterion("test_item is null");
            return (Criteria) this;
        }

        public Criteria andTestItemIsNotNull() {
            addCriterion("test_item is not null");
            return (Criteria) this;
        }

        public Criteria andTestItemEqualTo(String value) {
            addCriterion("test_item =", value, "testItem");
            return (Criteria) this;
        }

        public Criteria andTestItemNotEqualTo(String value) {
            addCriterion("test_item <>", value, "testItem");
            return (Criteria) this;
        }

        public Criteria andTestItemGreaterThan(String value) {
            addCriterion("test_item >", value, "testItem");
            return (Criteria) this;
        }

        public Criteria andTestItemGreaterThanOrEqualTo(String value) {
            addCriterion("test_item >=", value, "testItem");
            return (Criteria) this;
        }

        public Criteria andTestItemLessThan(String value) {
            addCriterion("test_item <", value, "testItem");
            return (Criteria) this;
        }

        public Criteria andTestItemLessThanOrEqualTo(String value) {
            addCriterion("test_item <=", value, "testItem");
            return (Criteria) this;
        }

        public Criteria andTestItemLike(String value) {
            addCriterion("test_item like", value, "testItem");
            return (Criteria) this;
        }

        public Criteria andTestItemNotLike(String value) {
            addCriterion("test_item not like", value, "testItem");
            return (Criteria) this;
        }

        public Criteria andTestItemIn(List<String> values) {
            addCriterion("test_item in", values, "testItem");
            return (Criteria) this;
        }

        public Criteria andTestItemNotIn(List<String> values) {
            addCriterion("test_item not in", values, "testItem");
            return (Criteria) this;
        }

        public Criteria andTestItemBetween(String value1, String value2) {
            addCriterion("test_item between", value1, value2, "testItem");
            return (Criteria) this;
        }

        public Criteria andTestItemNotBetween(String value1, String value2) {
            addCriterion("test_item not between", value1, value2, "testItem");
            return (Criteria) this;
        }

        public Criteria andUnitPriceIsNull() {
            addCriterion("unit_price is null");
            return (Criteria) this;
        }

        public Criteria andUnitPriceIsNotNull() {
            addCriterion("unit_price is not null");
            return (Criteria) this;
        }

        public Criteria andUnitPriceEqualTo(String value) {
            addCriterion("unit_price =", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceNotEqualTo(String value) {
            addCriterion("unit_price <>", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceGreaterThan(String value) {
            addCriterion("unit_price >", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceGreaterThanOrEqualTo(String value) {
            addCriterion("unit_price >=", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceLessThan(String value) {
            addCriterion("unit_price <", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceLessThanOrEqualTo(String value) {
            addCriterion("unit_price <=", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceLike(String value) {
            addCriterion("unit_price like", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceNotLike(String value) {
            addCriterion("unit_price not like", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceIn(List<String> values) {
            addCriterion("unit_price in", values, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceNotIn(List<String> values) {
            addCriterion("unit_price not in", values, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceBetween(String value1, String value2) {
            addCriterion("unit_price between", value1, value2, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceNotBetween(String value1, String value2) {
            addCriterion("unit_price not between", value1, value2, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andQtyIsNull() {
            addCriterion("qty is null");
            return (Criteria) this;
        }

        public Criteria andQtyIsNotNull() {
            addCriterion("qty is not null");
            return (Criteria) this;
        }

        public Criteria andQtyEqualTo(String value) {
            addCriterion("qty =", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyNotEqualTo(String value) {
            addCriterion("qty <>", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyGreaterThan(String value) {
            addCriterion("qty >", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyGreaterThanOrEqualTo(String value) {
            addCriterion("qty >=", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyLessThan(String value) {
            addCriterion("qty <", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyLessThanOrEqualTo(String value) {
            addCriterion("qty <=", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyLike(String value) {
            addCriterion("qty like", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyNotLike(String value) {
            addCriterion("qty not like", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyIn(List<String> values) {
            addCriterion("qty in", values, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyNotIn(List<String> values) {
            addCriterion("qty not in", values, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyBetween(String value1, String value2) {
            addCriterion("qty between", value1, value2, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyNotBetween(String value1, String value2) {
            addCriterion("qty not between", value1, value2, "qty");
            return (Criteria) this;
        }

        public Criteria andAmountRmbIsNull() {
            addCriterion("amount_rmb is null");
            return (Criteria) this;
        }

        public Criteria andAmountRmbIsNotNull() {
            addCriterion("amount_rmb is not null");
            return (Criteria) this;
        }

        public Criteria andAmountRmbEqualTo(String value) {
            addCriterion("amount_rmb =", value, "amountRmb");
            return (Criteria) this;
        }

        public Criteria andAmountRmbNotEqualTo(String value) {
            addCriterion("amount_rmb <>", value, "amountRmb");
            return (Criteria) this;
        }

        public Criteria andAmountRmbGreaterThan(String value) {
            addCriterion("amount_rmb >", value, "amountRmb");
            return (Criteria) this;
        }

        public Criteria andAmountRmbGreaterThanOrEqualTo(String value) {
            addCriterion("amount_rmb >=", value, "amountRmb");
            return (Criteria) this;
        }

        public Criteria andAmountRmbLessThan(String value) {
            addCriterion("amount_rmb <", value, "amountRmb");
            return (Criteria) this;
        }

        public Criteria andAmountRmbLessThanOrEqualTo(String value) {
            addCriterion("amount_rmb <=", value, "amountRmb");
            return (Criteria) this;
        }

        public Criteria andAmountRmbLike(String value) {
            addCriterion("amount_rmb like", value, "amountRmb");
            return (Criteria) this;
        }

        public Criteria andAmountRmbNotLike(String value) {
            addCriterion("amount_rmb not like", value, "amountRmb");
            return (Criteria) this;
        }

        public Criteria andAmountRmbIn(List<String> values) {
            addCriterion("amount_rmb in", values, "amountRmb");
            return (Criteria) this;
        }

        public Criteria andAmountRmbNotIn(List<String> values) {
            addCriterion("amount_rmb not in", values, "amountRmb");
            return (Criteria) this;
        }

        public Criteria andAmountRmbBetween(String value1, String value2) {
            addCriterion("amount_rmb between", value1, value2, "amountRmb");
            return (Criteria) this;
        }

        public Criteria andAmountRmbNotBetween(String value1, String value2) {
            addCriterion("amount_rmb not between", value1, value2, "amountRmb");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_quotation_item
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 27 16:19:50 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_quotation_item
     *
     * @mbg.generated Tue Dec 27 16:19:50 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}