package com.libiao.customer.dal.model;

import java.io.Serializable;

public class TestApplicationSample implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_application_sample.id
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_application_sample.application_form_id
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    private Long applicationFormId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_application_sample.application_num
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    private String applicationNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_application_sample.sample_name
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    private String sampleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_application_sample.sample_model
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    private String sampleModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_application_sample.sample_material
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    private String sampleMaterial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_application_sample.sample_description
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    private String sampleDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_application_sample
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_application_sample.id
     *
     * @return the value of test_application_sample.id
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_application_sample.id
     *
     * @param id the value for test_application_sample.id
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_application_sample.application_form_id
     *
     * @return the value of test_application_sample.application_form_id
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    public Long getApplicationFormId() {
        return applicationFormId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_application_sample.application_form_id
     *
     * @param applicationFormId the value for test_application_sample.application_form_id
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    public void setApplicationFormId(Long applicationFormId) {
        this.applicationFormId = applicationFormId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_application_sample.application_num
     *
     * @return the value of test_application_sample.application_num
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    public String getApplicationNum() {
        return applicationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_application_sample.application_num
     *
     * @param applicationNum the value for test_application_sample.application_num
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    public void setApplicationNum(String applicationNum) {
        this.applicationNum = applicationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_application_sample.sample_name
     *
     * @return the value of test_application_sample.sample_name
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    public String getSampleName() {
        return sampleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_application_sample.sample_name
     *
     * @param sampleName the value for test_application_sample.sample_name
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    public void setSampleName(String sampleName) {
        this.sampleName = sampleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_application_sample.sample_model
     *
     * @return the value of test_application_sample.sample_model
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    public String getSampleModel() {
        return sampleModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_application_sample.sample_model
     *
     * @param sampleModel the value for test_application_sample.sample_model
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    public void setSampleModel(String sampleModel) {
        this.sampleModel = sampleModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_application_sample.sample_material
     *
     * @return the value of test_application_sample.sample_material
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    public String getSampleMaterial() {
        return sampleMaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_application_sample.sample_material
     *
     * @param sampleMaterial the value for test_application_sample.sample_material
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    public void setSampleMaterial(String sampleMaterial) {
        this.sampleMaterial = sampleMaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_application_sample.sample_description
     *
     * @return the value of test_application_sample.sample_description
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    public String getSampleDescription() {
        return sampleDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_application_sample.sample_description
     *
     * @param sampleDescription the value for test_application_sample.sample_description
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    public void setSampleDescription(String sampleDescription) {
        this.sampleDescription = sampleDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_sample
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", applicationFormId=").append(applicationFormId);
        sb.append(", applicationNum=").append(applicationNum);
        sb.append(", sampleName=").append(sampleName);
        sb.append(", sampleModel=").append(sampleModel);
        sb.append(", sampleMaterial=").append(sampleMaterial);
        sb.append(", sampleDescription=").append(sampleDescription);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}