package com.libiao.customer.dal.model;

import java.io.Serializable;

public class TestQuotationGoods implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation_goods.id
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation_goods.quotation_num
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    private String quotationNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation_goods.goods_id
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation_goods.goods_name
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation_goods.hs_code
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    private String hsCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation_goods.material
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    private String material;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation_goods.export_country
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    private String exportCountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation_goods.standard
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    private String standard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation_goods.test_period
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    private Integer testPeriod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation_goods.sample_num
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    private String sampleNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation_goods.service
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    private Byte service;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation_goods.amount
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation_goods.reprot_type
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    private String reprotType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation_goods.org_price
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    private Integer orgPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation_goods.discount
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    private Integer discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_quotation_goods.report_amt
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    private Integer reportAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_quotation_goods
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation_goods.id
     *
     * @return the value of test_quotation_goods.id
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation_goods.id
     *
     * @param id the value for test_quotation_goods.id
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation_goods.quotation_num
     *
     * @return the value of test_quotation_goods.quotation_num
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public String getQuotationNum() {
        return quotationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation_goods.quotation_num
     *
     * @param quotationNum the value for test_quotation_goods.quotation_num
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public void setQuotationNum(String quotationNum) {
        this.quotationNum = quotationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation_goods.goods_id
     *
     * @return the value of test_quotation_goods.goods_id
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation_goods.goods_id
     *
     * @param goodsId the value for test_quotation_goods.goods_id
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation_goods.goods_name
     *
     * @return the value of test_quotation_goods.goods_name
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation_goods.goods_name
     *
     * @param goodsName the value for test_quotation_goods.goods_name
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation_goods.hs_code
     *
     * @return the value of test_quotation_goods.hs_code
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public String getHsCode() {
        return hsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation_goods.hs_code
     *
     * @param hsCode the value for test_quotation_goods.hs_code
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public void setHsCode(String hsCode) {
        this.hsCode = hsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation_goods.material
     *
     * @return the value of test_quotation_goods.material
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public String getMaterial() {
        return material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation_goods.material
     *
     * @param material the value for test_quotation_goods.material
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public void setMaterial(String material) {
        this.material = material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation_goods.export_country
     *
     * @return the value of test_quotation_goods.export_country
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public String getExportCountry() {
        return exportCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation_goods.export_country
     *
     * @param exportCountry the value for test_quotation_goods.export_country
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public void setExportCountry(String exportCountry) {
        this.exportCountry = exportCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation_goods.standard
     *
     * @return the value of test_quotation_goods.standard
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public String getStandard() {
        return standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation_goods.standard
     *
     * @param standard the value for test_quotation_goods.standard
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public void setStandard(String standard) {
        this.standard = standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation_goods.test_period
     *
     * @return the value of test_quotation_goods.test_period
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public Integer getTestPeriod() {
        return testPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation_goods.test_period
     *
     * @param testPeriod the value for test_quotation_goods.test_period
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public void setTestPeriod(Integer testPeriod) {
        this.testPeriod = testPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation_goods.sample_num
     *
     * @return the value of test_quotation_goods.sample_num
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public String getSampleNum() {
        return sampleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation_goods.sample_num
     *
     * @param sampleNum the value for test_quotation_goods.sample_num
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public void setSampleNum(String sampleNum) {
        this.sampleNum = sampleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation_goods.service
     *
     * @return the value of test_quotation_goods.service
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public Byte getService() {
        return service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation_goods.service
     *
     * @param service the value for test_quotation_goods.service
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public void setService(Byte service) {
        this.service = service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation_goods.amount
     *
     * @return the value of test_quotation_goods.amount
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation_goods.amount
     *
     * @param amount the value for test_quotation_goods.amount
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation_goods.reprot_type
     *
     * @return the value of test_quotation_goods.reprot_type
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public String getReprotType() {
        return reprotType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation_goods.reprot_type
     *
     * @param reprotType the value for test_quotation_goods.reprot_type
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public void setReprotType(String reprotType) {
        this.reprotType = reprotType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation_goods.org_price
     *
     * @return the value of test_quotation_goods.org_price
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public Integer getOrgPrice() {
        return orgPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation_goods.org_price
     *
     * @param orgPrice the value for test_quotation_goods.org_price
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public void setOrgPrice(Integer orgPrice) {
        this.orgPrice = orgPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation_goods.discount
     *
     * @return the value of test_quotation_goods.discount
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public Integer getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation_goods.discount
     *
     * @param discount the value for test_quotation_goods.discount
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_quotation_goods.report_amt
     *
     * @return the value of test_quotation_goods.report_amt
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public Integer getReportAmt() {
        return reportAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_quotation_goods.report_amt
     *
     * @param reportAmt the value for test_quotation_goods.report_amt
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    public void setReportAmt(Integer reportAmt) {
        this.reportAmt = reportAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_goods
     *
     * @mbg.generated Wed Dec 28 09:44:45 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", quotationNum=").append(quotationNum);
        sb.append(", goodsId=").append(goodsId);
        sb.append(", goodsName=").append(goodsName);
        sb.append(", hsCode=").append(hsCode);
        sb.append(", material=").append(material);
        sb.append(", exportCountry=").append(exportCountry);
        sb.append(", standard=").append(standard);
        sb.append(", testPeriod=").append(testPeriod);
        sb.append(", sampleNum=").append(sampleNum);
        sb.append(", service=").append(service);
        sb.append(", amount=").append(amount);
        sb.append(", reprotType=").append(reprotType);
        sb.append(", orgPrice=").append(orgPrice);
        sb.append(", discount=").append(discount);
        sb.append(", reportAmt=").append(reportAmt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}