package com.libiao.customer.dal.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TestBusinessExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_business
     *
     * @mbg.generated Sat Dec 24 14:02:25 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_business
     *
     * @mbg.generated Sat Dec 24 14:02:25 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_business
     *
     * @mbg.generated Sat Dec 24 14:02:25 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_business
     *
     * @mbg.generated Sat Dec 24 14:02:25 CST 2022
     */
    public TestBusinessExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_business
     *
     * @mbg.generated Sat Dec 24 14:02:25 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_business
     *
     * @mbg.generated Sat Dec 24 14:02:25 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_business
     *
     * @mbg.generated Sat Dec 24 14:02:25 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_business
     *
     * @mbg.generated Sat Dec 24 14:02:25 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_business
     *
     * @mbg.generated Sat Dec 24 14:02:25 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_business
     *
     * @mbg.generated Sat Dec 24 14:02:25 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_business
     *
     * @mbg.generated Sat Dec 24 14:02:25 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_business
     *
     * @mbg.generated Sat Dec 24 14:02:25 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_business
     *
     * @mbg.generated Sat Dec 24 14:02:25 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_business
     *
     * @mbg.generated Sat Dec 24 14:02:25 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_business
     *
     * @mbg.generated Sat Dec 24 14:02:25 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andClientIdIsNull() {
            addCriterion("client_id is null");
            return (Criteria) this;
        }

        public Criteria andClientIdIsNotNull() {
            addCriterion("client_id is not null");
            return (Criteria) this;
        }

        public Criteria andClientIdEqualTo(Long value) {
            addCriterion("client_id =", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotEqualTo(Long value) {
            addCriterion("client_id <>", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdGreaterThan(Long value) {
            addCriterion("client_id >", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdGreaterThanOrEqualTo(Long value) {
            addCriterion("client_id >=", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLessThan(Long value) {
            addCriterion("client_id <", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLessThanOrEqualTo(Long value) {
            addCriterion("client_id <=", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdIn(List<Long> values) {
            addCriterion("client_id in", values, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotIn(List<Long> values) {
            addCriterion("client_id not in", values, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdBetween(Long value1, Long value2) {
            addCriterion("client_id between", value1, value2, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotBetween(Long value1, Long value2) {
            addCriterion("client_id not between", value1, value2, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientNameIsNull() {
            addCriterion("client_name is null");
            return (Criteria) this;
        }

        public Criteria andClientNameIsNotNull() {
            addCriterion("client_name is not null");
            return (Criteria) this;
        }

        public Criteria andClientNameEqualTo(String value) {
            addCriterion("client_name =", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameNotEqualTo(String value) {
            addCriterion("client_name <>", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameGreaterThan(String value) {
            addCriterion("client_name >", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameGreaterThanOrEqualTo(String value) {
            addCriterion("client_name >=", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameLessThan(String value) {
            addCriterion("client_name <", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameLessThanOrEqualTo(String value) {
            addCriterion("client_name <=", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameLike(String value) {
            addCriterion("client_name like", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameNotLike(String value) {
            addCriterion("client_name not like", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameIn(List<String> values) {
            addCriterion("client_name in", values, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameNotIn(List<String> values) {
            addCriterion("client_name not in", values, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameBetween(String value1, String value2) {
            addCriterion("client_name between", value1, value2, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameNotBetween(String value1, String value2) {
            addCriterion("client_name not between", value1, value2, "clientName");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Byte value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Byte value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Byte value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Byte value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Byte value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Byte> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Byte> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Byte value1, Byte value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andHsCodeIsNull() {
            addCriterion("hs_code is null");
            return (Criteria) this;
        }

        public Criteria andHsCodeIsNotNull() {
            addCriterion("hs_code is not null");
            return (Criteria) this;
        }

        public Criteria andHsCodeEqualTo(String value) {
            addCriterion("hs_code =", value, "hsCode");
            return (Criteria) this;
        }

        public Criteria andHsCodeNotEqualTo(String value) {
            addCriterion("hs_code <>", value, "hsCode");
            return (Criteria) this;
        }

        public Criteria andHsCodeGreaterThan(String value) {
            addCriterion("hs_code >", value, "hsCode");
            return (Criteria) this;
        }

        public Criteria andHsCodeGreaterThanOrEqualTo(String value) {
            addCriterion("hs_code >=", value, "hsCode");
            return (Criteria) this;
        }

        public Criteria andHsCodeLessThan(String value) {
            addCriterion("hs_code <", value, "hsCode");
            return (Criteria) this;
        }

        public Criteria andHsCodeLessThanOrEqualTo(String value) {
            addCriterion("hs_code <=", value, "hsCode");
            return (Criteria) this;
        }

        public Criteria andHsCodeLike(String value) {
            addCriterion("hs_code like", value, "hsCode");
            return (Criteria) this;
        }

        public Criteria andHsCodeNotLike(String value) {
            addCriterion("hs_code not like", value, "hsCode");
            return (Criteria) this;
        }

        public Criteria andHsCodeIn(List<String> values) {
            addCriterion("hs_code in", values, "hsCode");
            return (Criteria) this;
        }

        public Criteria andHsCodeNotIn(List<String> values) {
            addCriterion("hs_code not in", values, "hsCode");
            return (Criteria) this;
        }

        public Criteria andHsCodeBetween(String value1, String value2) {
            addCriterion("hs_code between", value1, value2, "hsCode");
            return (Criteria) this;
        }

        public Criteria andHsCodeNotBetween(String value1, String value2) {
            addCriterion("hs_code not between", value1, value2, "hsCode");
            return (Criteria) this;
        }

        public Criteria andExportCountryIdIsNull() {
            addCriterion("export_country_id is null");
            return (Criteria) this;
        }

        public Criteria andExportCountryIdIsNotNull() {
            addCriterion("export_country_id is not null");
            return (Criteria) this;
        }

        public Criteria andExportCountryIdEqualTo(Integer value) {
            addCriterion("export_country_id =", value, "exportCountryId");
            return (Criteria) this;
        }

        public Criteria andExportCountryIdNotEqualTo(Integer value) {
            addCriterion("export_country_id <>", value, "exportCountryId");
            return (Criteria) this;
        }

        public Criteria andExportCountryIdGreaterThan(Integer value) {
            addCriterion("export_country_id >", value, "exportCountryId");
            return (Criteria) this;
        }

        public Criteria andExportCountryIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("export_country_id >=", value, "exportCountryId");
            return (Criteria) this;
        }

        public Criteria andExportCountryIdLessThan(Integer value) {
            addCriterion("export_country_id <", value, "exportCountryId");
            return (Criteria) this;
        }

        public Criteria andExportCountryIdLessThanOrEqualTo(Integer value) {
            addCriterion("export_country_id <=", value, "exportCountryId");
            return (Criteria) this;
        }

        public Criteria andExportCountryIdIn(List<Integer> values) {
            addCriterion("export_country_id in", values, "exportCountryId");
            return (Criteria) this;
        }

        public Criteria andExportCountryIdNotIn(List<Integer> values) {
            addCriterion("export_country_id not in", values, "exportCountryId");
            return (Criteria) this;
        }

        public Criteria andExportCountryIdBetween(Integer value1, Integer value2) {
            addCriterion("export_country_id between", value1, value2, "exportCountryId");
            return (Criteria) this;
        }

        public Criteria andExportCountryIdNotBetween(Integer value1, Integer value2) {
            addCriterion("export_country_id not between", value1, value2, "exportCountryId");
            return (Criteria) this;
        }

        public Criteria andTestStandardIsNull() {
            addCriterion("test_standard is null");
            return (Criteria) this;
        }

        public Criteria andTestStandardIsNotNull() {
            addCriterion("test_standard is not null");
            return (Criteria) this;
        }

        public Criteria andTestStandardEqualTo(String value) {
            addCriterion("test_standard =", value, "testStandard");
            return (Criteria) this;
        }

        public Criteria andTestStandardNotEqualTo(String value) {
            addCriterion("test_standard <>", value, "testStandard");
            return (Criteria) this;
        }

        public Criteria andTestStandardGreaterThan(String value) {
            addCriterion("test_standard >", value, "testStandard");
            return (Criteria) this;
        }

        public Criteria andTestStandardGreaterThanOrEqualTo(String value) {
            addCriterion("test_standard >=", value, "testStandard");
            return (Criteria) this;
        }

        public Criteria andTestStandardLessThan(String value) {
            addCriterion("test_standard <", value, "testStandard");
            return (Criteria) this;
        }

        public Criteria andTestStandardLessThanOrEqualTo(String value) {
            addCriterion("test_standard <=", value, "testStandard");
            return (Criteria) this;
        }

        public Criteria andTestStandardLike(String value) {
            addCriterion("test_standard like", value, "testStandard");
            return (Criteria) this;
        }

        public Criteria andTestStandardNotLike(String value) {
            addCriterion("test_standard not like", value, "testStandard");
            return (Criteria) this;
        }

        public Criteria andTestStandardIn(List<String> values) {
            addCriterion("test_standard in", values, "testStandard");
            return (Criteria) this;
        }

        public Criteria andTestStandardNotIn(List<String> values) {
            addCriterion("test_standard not in", values, "testStandard");
            return (Criteria) this;
        }

        public Criteria andTestStandardBetween(String value1, String value2) {
            addCriterion("test_standard between", value1, value2, "testStandard");
            return (Criteria) this;
        }

        public Criteria andTestStandardNotBetween(String value1, String value2) {
            addCriterion("test_standard not between", value1, value2, "testStandard");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andMaterialIsNull() {
            addCriterion("material is null");
            return (Criteria) this;
        }

        public Criteria andMaterialIsNotNull() {
            addCriterion("material is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialEqualTo(String value) {
            addCriterion("material =", value, "material");
            return (Criteria) this;
        }

        public Criteria andMaterialNotEqualTo(String value) {
            addCriterion("material <>", value, "material");
            return (Criteria) this;
        }

        public Criteria andMaterialGreaterThan(String value) {
            addCriterion("material >", value, "material");
            return (Criteria) this;
        }

        public Criteria andMaterialGreaterThanOrEqualTo(String value) {
            addCriterion("material >=", value, "material");
            return (Criteria) this;
        }

        public Criteria andMaterialLessThan(String value) {
            addCriterion("material <", value, "material");
            return (Criteria) this;
        }

        public Criteria andMaterialLessThanOrEqualTo(String value) {
            addCriterion("material <=", value, "material");
            return (Criteria) this;
        }

        public Criteria andMaterialLike(String value) {
            addCriterion("material like", value, "material");
            return (Criteria) this;
        }

        public Criteria andMaterialNotLike(String value) {
            addCriterion("material not like", value, "material");
            return (Criteria) this;
        }

        public Criteria andMaterialIn(List<String> values) {
            addCriterion("material in", values, "material");
            return (Criteria) this;
        }

        public Criteria andMaterialNotIn(List<String> values) {
            addCriterion("material not in", values, "material");
            return (Criteria) this;
        }

        public Criteria andMaterialBetween(String value1, String value2) {
            addCriterion("material between", value1, value2, "material");
            return (Criteria) this;
        }

        public Criteria andMaterialNotBetween(String value1, String value2) {
            addCriterion("material not between", value1, value2, "material");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Integer value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Integer value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Integer value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Integer value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Integer value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Integer> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Integer> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Integer value1, Integer value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andTotalSampleCntIsNull() {
            addCriterion("total_sample_cnt is null");
            return (Criteria) this;
        }

        public Criteria andTotalSampleCntIsNotNull() {
            addCriterion("total_sample_cnt is not null");
            return (Criteria) this;
        }

        public Criteria andTotalSampleCntEqualTo(Integer value) {
            addCriterion("total_sample_cnt =", value, "totalSampleCnt");
            return (Criteria) this;
        }

        public Criteria andTotalSampleCntNotEqualTo(Integer value) {
            addCriterion("total_sample_cnt <>", value, "totalSampleCnt");
            return (Criteria) this;
        }

        public Criteria andTotalSampleCntGreaterThan(Integer value) {
            addCriterion("total_sample_cnt >", value, "totalSampleCnt");
            return (Criteria) this;
        }

        public Criteria andTotalSampleCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_sample_cnt >=", value, "totalSampleCnt");
            return (Criteria) this;
        }

        public Criteria andTotalSampleCntLessThan(Integer value) {
            addCriterion("total_sample_cnt <", value, "totalSampleCnt");
            return (Criteria) this;
        }

        public Criteria andTotalSampleCntLessThanOrEqualTo(Integer value) {
            addCriterion("total_sample_cnt <=", value, "totalSampleCnt");
            return (Criteria) this;
        }

        public Criteria andTotalSampleCntIn(List<Integer> values) {
            addCriterion("total_sample_cnt in", values, "totalSampleCnt");
            return (Criteria) this;
        }

        public Criteria andTotalSampleCntNotIn(List<Integer> values) {
            addCriterion("total_sample_cnt not in", values, "totalSampleCnt");
            return (Criteria) this;
        }

        public Criteria andTotalSampleCntBetween(Integer value1, Integer value2) {
            addCriterion("total_sample_cnt between", value1, value2, "totalSampleCnt");
            return (Criteria) this;
        }

        public Criteria andTotalSampleCntNotBetween(Integer value1, Integer value2) {
            addCriterion("total_sample_cnt not between", value1, value2, "totalSampleCnt");
            return (Criteria) this;
        }

        public Criteria andTestPeriodIsNull() {
            addCriterion("test_period is null");
            return (Criteria) this;
        }

        public Criteria andTestPeriodIsNotNull() {
            addCriterion("test_period is not null");
            return (Criteria) this;
        }

        public Criteria andTestPeriodEqualTo(Integer value) {
            addCriterion("test_period =", value, "testPeriod");
            return (Criteria) this;
        }

        public Criteria andTestPeriodNotEqualTo(Integer value) {
            addCriterion("test_period <>", value, "testPeriod");
            return (Criteria) this;
        }

        public Criteria andTestPeriodGreaterThan(Integer value) {
            addCriterion("test_period >", value, "testPeriod");
            return (Criteria) this;
        }

        public Criteria andTestPeriodGreaterThanOrEqualTo(Integer value) {
            addCriterion("test_period >=", value, "testPeriod");
            return (Criteria) this;
        }

        public Criteria andTestPeriodLessThan(Integer value) {
            addCriterion("test_period <", value, "testPeriod");
            return (Criteria) this;
        }

        public Criteria andTestPeriodLessThanOrEqualTo(Integer value) {
            addCriterion("test_period <=", value, "testPeriod");
            return (Criteria) this;
        }

        public Criteria andTestPeriodIn(List<Integer> values) {
            addCriterion("test_period in", values, "testPeriod");
            return (Criteria) this;
        }

        public Criteria andTestPeriodNotIn(List<Integer> values) {
            addCriterion("test_period not in", values, "testPeriod");
            return (Criteria) this;
        }

        public Criteria andTestPeriodBetween(Integer value1, Integer value2) {
            addCriterion("test_period between", value1, value2, "testPeriod");
            return (Criteria) this;
        }

        public Criteria andTestPeriodNotBetween(Integer value1, Integer value2) {
            addCriterion("test_period not between", value1, value2, "testPeriod");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_business
     *
     * @mbg.generated do_not_delete_during_merge Sat Dec 24 14:02:25 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_business
     *
     * @mbg.generated Sat Dec 24 14:02:25 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}