package com.libiao.customer.dal.model;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gmt_create
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gmt_modify
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    private Date gmtModify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.permission
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    private String permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nickname
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone_num
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    private String phoneNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.status
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.account_type
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    private String accountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.org_no
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    private String orgNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.role_id
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.created_by
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    private Long createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.com
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    private String com;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.com_id
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    private Long comId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.decide_role
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    private String decideRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.depart
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    private String depart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.pos
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    private String pos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.work_state
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    private String workState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birthday
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.main_contact
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    private String mainContact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.flex_obj
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    private String flexObj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gmt_create
     *
     * @return the value of user.gmt_create
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gmt_create
     *
     * @param gmtCreate the value for user.gmt_create
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gmt_modify
     *
     * @return the value of user.gmt_modify
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gmt_modify
     *
     * @param gmtModify the value for user.gmt_modify
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.permission
     *
     * @return the value of user.permission
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.permission
     *
     * @param permission the value for user.permission
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public void setPermission(String permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nickname
     *
     * @return the value of user.nickname
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nickname
     *
     * @param nickname the value for user.nickname
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone_num
     *
     * @return the value of user.phone_num
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone_num
     *
     * @param phoneNum the value for user.phone_num
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.status
     *
     * @return the value of user.status
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.status
     *
     * @param status the value for user.status
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.account_type
     *
     * @return the value of user.account_type
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.account_type
     *
     * @param accountType the value for user.account_type
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.org_no
     *
     * @return the value of user.org_no
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public String getOrgNo() {
        return orgNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.org_no
     *
     * @param orgNo the value for user.org_no
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public void setOrgNo(String orgNo) {
        this.orgNo = orgNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.role_id
     *
     * @return the value of user.role_id
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.role_id
     *
     * @param roleId the value for user.role_id
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.created_by
     *
     * @return the value of user.created_by
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.created_by
     *
     * @param createdBy the value for user.created_by
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.com
     *
     * @return the value of user.com
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public String getCom() {
        return com;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.com
     *
     * @param com the value for user.com
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public void setCom(String com) {
        this.com = com;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.com_id
     *
     * @return the value of user.com_id
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public Long getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.com_id
     *
     * @param comId the value for user.com_id
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public void setComId(Long comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.decide_role
     *
     * @return the value of user.decide_role
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public String getDecideRole() {
        return decideRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.decide_role
     *
     * @param decideRole the value for user.decide_role
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public void setDecideRole(String decideRole) {
        this.decideRole = decideRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.depart
     *
     * @return the value of user.depart
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public String getDepart() {
        return depart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.depart
     *
     * @param depart the value for user.depart
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public void setDepart(String depart) {
        this.depart = depart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.pos
     *
     * @return the value of user.pos
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public String getPos() {
        return pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.pos
     *
     * @param pos the value for user.pos
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public void setPos(String pos) {
        this.pos = pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.work_state
     *
     * @return the value of user.work_state
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public String getWorkState() {
        return workState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.work_state
     *
     * @param workState the value for user.work_state
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public void setWorkState(String workState) {
        this.workState = workState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birthday
     *
     * @return the value of user.birthday
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birthday
     *
     * @param birthday the value for user.birthday
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.main_contact
     *
     * @return the value of user.main_contact
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public String getMainContact() {
        return mainContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.main_contact
     *
     * @param mainContact the value for user.main_contact
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public void setMainContact(String mainContact) {
        this.mainContact = mainContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.flex_obj
     *
     * @return the value of user.flex_obj
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public String getFlexObj() {
        return flexObj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.flex_obj
     *
     * @param flexObj the value for user.flex_obj
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    public void setFlexObj(String flexObj) {
        this.flexObj = flexObj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Dec 28 14:31:01 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModify=").append(gmtModify);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", permission=").append(permission);
        sb.append(", nickname=").append(nickname);
        sb.append(", phoneNum=").append(phoneNum);
        sb.append(", email=").append(email);
        sb.append(", status=").append(status);
        sb.append(", sex=").append(sex);
        sb.append(", accountType=").append(accountType);
        sb.append(", orgNo=").append(orgNo);
        sb.append(", roleId=").append(roleId);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", com=").append(com);
        sb.append(", comId=").append(comId);
        sb.append(", phone=").append(phone);
        sb.append(", decideRole=").append(decideRole);
        sb.append(", depart=").append(depart);
        sb.append(", pos=").append(pos);
        sb.append(", workState=").append(workState);
        sb.append(", birthday=").append(birthday);
        sb.append(", mainContact=").append(mainContact);
        sb.append(", flexObj=").append(flexObj);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}