package com.libiao.customer.dal.mapper;

import com.libiao.customer.dal.model.BasicStandard;
import com.libiao.customer.dal.model.BasicStandardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BasicStandardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_standard
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    long countByExample(BasicStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_standard
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    int deleteByExample(BasicStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_standard
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_standard
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    int insert(BasicStandard row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_standard
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    int insertSelective(BasicStandard row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_standard
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    List<BasicStandard> selectByExample(BasicStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_standard
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    BasicStandard selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_standard
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    int updateByExampleSelective(@Param("row") BasicStandard row, @Param("example") BasicStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_standard
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    int updateByExample(@Param("row") BasicStandard row, @Param("example") BasicStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_standard
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    int updateByPrimaryKeySelective(BasicStandard row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_standard
     *
     * @mbg.generated Thu Dec 29 10:39:08 CST 2022
     */
    int updateByPrimaryKey(BasicStandard row);
}