package com.libiao.customer.dal.mapper;

import com.libiao.customer.dal.model.BasicTestItem;
import com.libiao.customer.dal.model.BasicTestItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BasicTestItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_test_item
     *
     * @mbg.generated Tue Dec 27 14:52:21 CST 2022
     */
    long countByExample(BasicTestItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_test_item
     *
     * @mbg.generated Tue Dec 27 14:52:21 CST 2022
     */
    int deleteByExample(BasicTestItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_test_item
     *
     * @mbg.generated Tue Dec 27 14:52:21 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_test_item
     *
     * @mbg.generated Tue Dec 27 14:52:21 CST 2022
     */
    int insert(BasicTestItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_test_item
     *
     * @mbg.generated Tue Dec 27 14:52:21 CST 2022
     */
    int insertSelective(BasicTestItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_test_item
     *
     * @mbg.generated Tue Dec 27 14:52:21 CST 2022
     */
    List<BasicTestItem> selectByExampleWithBLOBs(BasicTestItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_test_item
     *
     * @mbg.generated Tue Dec 27 14:52:21 CST 2022
     */
    List<BasicTestItem> selectByExample(BasicTestItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_test_item
     *
     * @mbg.generated Tue Dec 27 14:52:21 CST 2022
     */
    BasicTestItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_test_item
     *
     * @mbg.generated Tue Dec 27 14:52:21 CST 2022
     */
    int updateByExampleSelective(@Param("row") BasicTestItem row, @Param("example") BasicTestItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_test_item
     *
     * @mbg.generated Tue Dec 27 14:52:21 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("row") BasicTestItem row, @Param("example") BasicTestItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_test_item
     *
     * @mbg.generated Tue Dec 27 14:52:21 CST 2022
     */
    int updateByExample(@Param("row") BasicTestItem row, @Param("example") BasicTestItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_test_item
     *
     * @mbg.generated Tue Dec 27 14:52:21 CST 2022
     */
    int updateByPrimaryKeySelective(BasicTestItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_test_item
     *
     * @mbg.generated Tue Dec 27 14:52:21 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(BasicTestItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_test_item
     *
     * @mbg.generated Tue Dec 27 14:52:21 CST 2022
     */
    int updateByPrimaryKey(BasicTestItem row);
}