package com.libiao.customer.dal.mapper;

import com.libiao.customer.dal.model.BasicGoodsMaterial;
import com.libiao.customer.dal.model.BasicGoodsMaterialExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BasicGoodsMaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_goods_material
     *
     * @mbg.generated Fri Jan 06 16:37:08 CST 2023
     */
    long countByExample(BasicGoodsMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_goods_material
     *
     * @mbg.generated Fri Jan 06 16:37:08 CST 2023
     */
    int deleteByExample(BasicGoodsMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_goods_material
     *
     * @mbg.generated Fri Jan 06 16:37:08 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_goods_material
     *
     * @mbg.generated Fri Jan 06 16:37:08 CST 2023
     */
    int insert(BasicGoodsMaterial row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_goods_material
     *
     * @mbg.generated Fri Jan 06 16:37:08 CST 2023
     */
    int insertSelective(BasicGoodsMaterial row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_goods_material
     *
     * @mbg.generated Fri Jan 06 16:37:08 CST 2023
     */
    List<BasicGoodsMaterial> selectByExample(BasicGoodsMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_goods_material
     *
     * @mbg.generated Fri Jan 06 16:37:08 CST 2023
     */
    BasicGoodsMaterial selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_goods_material
     *
     * @mbg.generated Fri Jan 06 16:37:08 CST 2023
     */
    int updateByExampleSelective(@Param("row") BasicGoodsMaterial row, @Param("example") BasicGoodsMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_goods_material
     *
     * @mbg.generated Fri Jan 06 16:37:08 CST 2023
     */
    int updateByExample(@Param("row") BasicGoodsMaterial row, @Param("example") BasicGoodsMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_goods_material
     *
     * @mbg.generated Fri Jan 06 16:37:08 CST 2023
     */
    int updateByPrimaryKeySelective(BasicGoodsMaterial row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_goods_material
     *
     * @mbg.generated Fri Jan 06 16:37:08 CST 2023
     */
    int updateByPrimaryKey(BasicGoodsMaterial row);
}