package com.libiao.customer.dal.mapper;

import com.libiao.customer.dal.model.CustomerBill;
import com.libiao.customer.dal.model.CustomerBillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_bill
     *
     * @mbg.generated Mon Jan 02 14:51:18 CST 2023
     */
    long countByExample(CustomerBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_bill
     *
     * @mbg.generated Mon Jan 02 14:51:18 CST 2023
     */
    int deleteByExample(CustomerBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_bill
     *
     * @mbg.generated Mon Jan 02 14:51:18 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_bill
     *
     * @mbg.generated Mon Jan 02 14:51:18 CST 2023
     */
    int insert(CustomerBill row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_bill
     *
     * @mbg.generated Mon Jan 02 14:51:18 CST 2023
     */
    int insertSelective(CustomerBill row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_bill
     *
     * @mbg.generated Mon Jan 02 14:51:18 CST 2023
     */
    List<CustomerBill> selectByExample(CustomerBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_bill
     *
     * @mbg.generated Mon Jan 02 14:51:18 CST 2023
     */
    CustomerBill selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_bill
     *
     * @mbg.generated Mon Jan 02 14:51:18 CST 2023
     */
    int updateByExampleSelective(@Param("row") CustomerBill row, @Param("example") CustomerBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_bill
     *
     * @mbg.generated Mon Jan 02 14:51:18 CST 2023
     */
    int updateByExample(@Param("row") CustomerBill row, @Param("example") CustomerBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_bill
     *
     * @mbg.generated Mon Jan 02 14:51:18 CST 2023
     */
    int updateByPrimaryKeySelective(CustomerBill row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_bill
     *
     * @mbg.generated Mon Jan 02 14:51:18 CST 2023
     */
    int updateByPrimaryKey(CustomerBill row);
}