package com.libiao.customer.dal.mapper;

import com.libiao.customer.dal.model.SystemParameter;
import com.libiao.customer.dal.model.SystemParameterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemParameterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated Tue Dec 27 17:53:50 CST 2022
     */
    long countByExample(SystemParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated Tue Dec 27 17:53:50 CST 2022
     */
    int deleteByExample(SystemParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated Tue Dec 27 17:53:50 CST 2022
     */
    int deleteByPrimaryKey(String paramKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated Tue Dec 27 17:53:50 CST 2022
     */
    int insert(SystemParameter row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated Tue Dec 27 17:53:50 CST 2022
     */
    int insertSelective(SystemParameter row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated Tue Dec 27 17:53:50 CST 2022
     */
    List<SystemParameter> selectByExample(SystemParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated Tue Dec 27 17:53:50 CST 2022
     */
    SystemParameter selectByPrimaryKey(String paramKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated Tue Dec 27 17:53:50 CST 2022
     */
    int updateByExampleSelective(@Param("row") SystemParameter row, @Param("example") SystemParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated Tue Dec 27 17:53:50 CST 2022
     */
    int updateByExample(@Param("row") SystemParameter row, @Param("example") SystemParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated Tue Dec 27 17:53:50 CST 2022
     */
    int updateByPrimaryKeySelective(SystemParameter row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated Tue Dec 27 17:53:50 CST 2022
     */
    int updateByPrimaryKey(SystemParameter row);
}