package com.libiao.customer.dal.mapper;

import com.libiao.customer.dal.model.TestQuotationGoods;
import com.libiao.customer.dal.model.TestQuotationGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestQuotationGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_goods
     *
     * @mbg.generated Tue Dec 27 16:19:38 CST 2022
     */
    long countByExample(TestQuotationGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_goods
     *
     * @mbg.generated Tue Dec 27 16:19:38 CST 2022
     */
    int deleteByExample(TestQuotationGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_goods
     *
     * @mbg.generated Tue Dec 27 16:19:38 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_goods
     *
     * @mbg.generated Tue Dec 27 16:19:38 CST 2022
     */
    int insert(TestQuotationGoods row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_goods
     *
     * @mbg.generated Tue Dec 27 16:19:38 CST 2022
     */
    int insertSelective(TestQuotationGoods row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_goods
     *
     * @mbg.generated Tue Dec 27 16:19:38 CST 2022
     */
    List<TestQuotationGoods> selectByExample(TestQuotationGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_goods
     *
     * @mbg.generated Tue Dec 27 16:19:38 CST 2022
     */
    TestQuotationGoods selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_goods
     *
     * @mbg.generated Tue Dec 27 16:19:38 CST 2022
     */
    int updateByExampleSelective(@Param("row") TestQuotationGoods row, @Param("example") TestQuotationGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_goods
     *
     * @mbg.generated Tue Dec 27 16:19:38 CST 2022
     */
    int updateByExample(@Param("row") TestQuotationGoods row, @Param("example") TestQuotationGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_goods
     *
     * @mbg.generated Tue Dec 27 16:19:38 CST 2022
     */
    int updateByPrimaryKeySelective(TestQuotationGoods row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_goods
     *
     * @mbg.generated Tue Dec 27 16:19:38 CST 2022
     */
    int updateByPrimaryKey(TestQuotationGoods row);
}