package com.libiao.customer.dal.mapper;

import com.libiao.customer.dal.model.TestBizItem;
import com.libiao.customer.dal.model.TestBizItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestBizItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_biz_item
     *
     * @mbg.generated Sat Dec 24 14:02:59 CST 2022
     */
    long countByExample(TestBizItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_biz_item
     *
     * @mbg.generated Sat Dec 24 14:02:59 CST 2022
     */
    int deleteByExample(TestBizItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_biz_item
     *
     * @mbg.generated Sat Dec 24 14:02:59 CST 2022
     */
    int deleteByPrimaryKey(@Param("testBizId") Long testBizId, @Param("testItemId") Integer testItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_biz_item
     *
     * @mbg.generated Sat Dec 24 14:02:59 CST 2022
     */
    int insert(TestBizItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_biz_item
     *
     * @mbg.generated Sat Dec 24 14:02:59 CST 2022
     */
    int insertSelective(TestBizItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_biz_item
     *
     * @mbg.generated Sat Dec 24 14:02:59 CST 2022
     */
    List<TestBizItem> selectByExample(TestBizItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_biz_item
     *
     * @mbg.generated Sat Dec 24 14:02:59 CST 2022
     */
    TestBizItem selectByPrimaryKey(@Param("testBizId") Long testBizId, @Param("testItemId") Integer testItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_biz_item
     *
     * @mbg.generated Sat Dec 24 14:02:59 CST 2022
     */
    int updateByExampleSelective(@Param("row") TestBizItem row, @Param("example") TestBizItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_biz_item
     *
     * @mbg.generated Sat Dec 24 14:02:59 CST 2022
     */
    int updateByExample(@Param("row") TestBizItem row, @Param("example") TestBizItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_biz_item
     *
     * @mbg.generated Sat Dec 24 14:02:59 CST 2022
     */
    int updateByPrimaryKeySelective(TestBizItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_biz_item
     *
     * @mbg.generated Sat Dec 24 14:02:59 CST 2022
     */
    int updateByPrimaryKey(TestBizItem row);
}