package com.libiao.customer.dal.mapper;

import com.libiao.customer.dal.model.TestQuotation;
import com.libiao.customer.dal.model.TestQuotationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestQuotationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation
     *
     * @mbg.generated Mon Jan 02 14:48:10 CST 2023
     */
    long countByExample(TestQuotationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation
     *
     * @mbg.generated Mon Jan 02 14:48:10 CST 2023
     */
    int deleteByExample(TestQuotationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation
     *
     * @mbg.generated Mon Jan 02 14:48:10 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation
     *
     * @mbg.generated Mon Jan 02 14:48:10 CST 2023
     */
    int insert(TestQuotation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation
     *
     * @mbg.generated Mon Jan 02 14:48:10 CST 2023
     */
    int insertSelective(TestQuotation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation
     *
     * @mbg.generated Mon Jan 02 14:48:10 CST 2023
     */
    List<TestQuotation> selectByExampleWithBLOBs(TestQuotationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation
     *
     * @mbg.generated Mon Jan 02 14:48:10 CST 2023
     */
    List<TestQuotation> selectByExample(TestQuotationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation
     *
     * @mbg.generated Mon Jan 02 14:48:10 CST 2023
     */
    TestQuotation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation
     *
     * @mbg.generated Mon Jan 02 14:48:10 CST 2023
     */
    int updateByExampleSelective(@Param("row") TestQuotation row, @Param("example") TestQuotationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation
     *
     * @mbg.generated Mon Jan 02 14:48:10 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("row") TestQuotation row, @Param("example") TestQuotationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation
     *
     * @mbg.generated Mon Jan 02 14:48:10 CST 2023
     */
    int updateByExample(@Param("row") TestQuotation row, @Param("example") TestQuotationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation
     *
     * @mbg.generated Mon Jan 02 14:48:10 CST 2023
     */
    int updateByPrimaryKeySelective(TestQuotation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation
     *
     * @mbg.generated Mon Jan 02 14:48:10 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(TestQuotation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation
     *
     * @mbg.generated Mon Jan 02 14:48:10 CST 2023
     */
    int updateByPrimaryKey(TestQuotation row);
}