package com.libiao.customer.dal.mapper;

import com.libiao.customer.dal.model.TestWorkOrderItem;
import com.libiao.customer.dal.model.TestWorkOrderItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestWorkOrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_work_order_item
     *
     * @mbg.generated Mon Jan 02 19:30:01 CST 2023
     */
    long countByExample(TestWorkOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_work_order_item
     *
     * @mbg.generated Mon Jan 02 19:30:01 CST 2023
     */
    int deleteByExample(TestWorkOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_work_order_item
     *
     * @mbg.generated Mon Jan 02 19:30:01 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_work_order_item
     *
     * @mbg.generated Mon Jan 02 19:30:01 CST 2023
     */
    int insert(TestWorkOrderItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_work_order_item
     *
     * @mbg.generated Mon Jan 02 19:30:01 CST 2023
     */
    int insertSelective(TestWorkOrderItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_work_order_item
     *
     * @mbg.generated Mon Jan 02 19:30:01 CST 2023
     */
    List<TestWorkOrderItem> selectByExample(TestWorkOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_work_order_item
     *
     * @mbg.generated Mon Jan 02 19:30:01 CST 2023
     */
    TestWorkOrderItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_work_order_item
     *
     * @mbg.generated Mon Jan 02 19:30:01 CST 2023
     */
    int updateByExampleSelective(@Param("row") TestWorkOrderItem row, @Param("example") TestWorkOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_work_order_item
     *
     * @mbg.generated Mon Jan 02 19:30:01 CST 2023
     */
    int updateByExample(@Param("row") TestWorkOrderItem row, @Param("example") TestWorkOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_work_order_item
     *
     * @mbg.generated Mon Jan 02 19:30:01 CST 2023
     */
    int updateByPrimaryKeySelective(TestWorkOrderItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_work_order_item
     *
     * @mbg.generated Mon Jan 02 19:30:01 CST 2023
     */
    int updateByPrimaryKey(TestWorkOrderItem row);
}