package com.libiao.customer.dal.mapper;

import com.libiao.customer.dal.model.TestItemMethodRel;
import com.libiao.customer.dal.model.TestItemMethodRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestItemMethodRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_item_method_rel
     *
     * @mbg.generated Mon Jan 02 16:00:37 CST 2023
     */
    long countByExample(TestItemMethodRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_item_method_rel
     *
     * @mbg.generated Mon Jan 02 16:00:37 CST 2023
     */
    int deleteByExample(TestItemMethodRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_item_method_rel
     *
     * @mbg.generated Mon Jan 02 16:00:37 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_item_method_rel
     *
     * @mbg.generated Mon Jan 02 16:00:37 CST 2023
     */
    int insert(TestItemMethodRel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_item_method_rel
     *
     * @mbg.generated Mon Jan 02 16:00:37 CST 2023
     */
    int insertSelective(TestItemMethodRel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_item_method_rel
     *
     * @mbg.generated Mon Jan 02 16:00:37 CST 2023
     */
    List<TestItemMethodRel> selectByExample(TestItemMethodRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_item_method_rel
     *
     * @mbg.generated Mon Jan 02 16:00:37 CST 2023
     */
    TestItemMethodRel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_item_method_rel
     *
     * @mbg.generated Mon Jan 02 16:00:37 CST 2023
     */
    int updateByExampleSelective(@Param("row") TestItemMethodRel row, @Param("example") TestItemMethodRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_item_method_rel
     *
     * @mbg.generated Mon Jan 02 16:00:37 CST 2023
     */
    int updateByExample(@Param("row") TestItemMethodRel row, @Param("example") TestItemMethodRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_item_method_rel
     *
     * @mbg.generated Mon Jan 02 16:00:37 CST 2023
     */
    int updateByPrimaryKeySelective(TestItemMethodRel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_item_method_rel
     *
     * @mbg.generated Mon Jan 02 16:00:37 CST 2023
     */
    int updateByPrimaryKey(TestItemMethodRel row);
}