package com.libiao.customer.dal.mapper;

import com.libiao.customer.dal.model.TestQuotationItem;
import com.libiao.customer.dal.model.TestQuotationItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestQuotationItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_item
     *
     * @mbg.generated Tue Dec 27 16:19:50 CST 2022
     */
    long countByExample(TestQuotationItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_item
     *
     * @mbg.generated Tue Dec 27 16:19:50 CST 2022
     */
    int deleteByExample(TestQuotationItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_item
     *
     * @mbg.generated Tue Dec 27 16:19:50 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_item
     *
     * @mbg.generated Tue Dec 27 16:19:50 CST 2022
     */
    int insert(TestQuotationItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_item
     *
     * @mbg.generated Tue Dec 27 16:19:50 CST 2022
     */
    int insertSelective(TestQuotationItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_item
     *
     * @mbg.generated Tue Dec 27 16:19:50 CST 2022
     */
    List<TestQuotationItem> selectByExample(TestQuotationItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_item
     *
     * @mbg.generated Tue Dec 27 16:19:50 CST 2022
     */
    TestQuotationItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_item
     *
     * @mbg.generated Tue Dec 27 16:19:50 CST 2022
     */
    int updateByExampleSelective(@Param("row") TestQuotationItem row, @Param("example") TestQuotationItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_item
     *
     * @mbg.generated Tue Dec 27 16:19:50 CST 2022
     */
    int updateByExample(@Param("row") TestQuotationItem row, @Param("example") TestQuotationItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_item
     *
     * @mbg.generated Tue Dec 27 16:19:50 CST 2022
     */
    int updateByPrimaryKeySelective(TestQuotationItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_quotation_item
     *
     * @mbg.generated Tue Dec 27 16:19:50 CST 2022
     */
    int updateByPrimaryKey(TestQuotationItem row);
}