package com.libiao.customer.dal.mapper;

import com.libiao.customer.dal.model.TestWorkOrder;
import com.libiao.customer.dal.model.TestWorkOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestWorkOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_work_order
     *
     * @mbg.generated Mon Jan 02 19:30:01 CST 2023
     */
    long countByExample(TestWorkOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_work_order
     *
     * @mbg.generated Mon Jan 02 19:30:01 CST 2023
     */
    int deleteByExample(TestWorkOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_work_order
     *
     * @mbg.generated Mon Jan 02 19:30:01 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_work_order
     *
     * @mbg.generated Mon Jan 02 19:30:01 CST 2023
     */
    int insert(TestWorkOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_work_order
     *
     * @mbg.generated Mon Jan 02 19:30:01 CST 2023
     */
    int insertSelective(TestWorkOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_work_order
     *
     * @mbg.generated Mon Jan 02 19:30:01 CST 2023
     */
    List<TestWorkOrder> selectByExample(TestWorkOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_work_order
     *
     * @mbg.generated Mon Jan 02 19:30:01 CST 2023
     */
    TestWorkOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_work_order
     *
     * @mbg.generated Mon Jan 02 19:30:01 CST 2023
     */
    int updateByExampleSelective(@Param("row") TestWorkOrder row, @Param("example") TestWorkOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_work_order
     *
     * @mbg.generated Mon Jan 02 19:30:01 CST 2023
     */
    int updateByExample(@Param("row") TestWorkOrder row, @Param("example") TestWorkOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_work_order
     *
     * @mbg.generated Mon Jan 02 19:30:01 CST 2023
     */
    int updateByPrimaryKeySelective(TestWorkOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_work_order
     *
     * @mbg.generated Mon Jan 02 19:30:01 CST 2023
     */
    int updateByPrimaryKey(TestWorkOrder row);
}