package com.libiao.customer.dal.mapper;

import com.libiao.customer.dal.model.TestApplicationSample;
import com.libiao.customer.dal.model.TestApplicationSampleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestApplicationSampleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_sample
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    long countByExample(TestApplicationSampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_sample
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    int deleteByExample(TestApplicationSampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_sample
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_sample
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    int insert(TestApplicationSample row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_sample
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    int insertSelective(TestApplicationSample row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_sample
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    List<TestApplicationSample> selectByExample(TestApplicationSampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_sample
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    TestApplicationSample selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_sample
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    int updateByExampleSelective(@Param("row") TestApplicationSample row, @Param("example") TestApplicationSampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_sample
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    int updateByExample(@Param("row") TestApplicationSample row, @Param("example") TestApplicationSampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_sample
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    int updateByPrimaryKeySelective(TestApplicationSample row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_sample
     *
     * @mbg.generated Sun Jan 01 14:43:46 CST 2023
     */
    int updateByPrimaryKey(TestApplicationSample row);
}