package com.libiao.customer.dal.mapper;

import com.libiao.customer.dal.model.TestApplicationForm;
import com.libiao.customer.dal.model.TestApplicationFormExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestApplicationFormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_form
     *
     * @mbg.generated Sat Dec 31 20:23:41 CST 2022
     */
    long countByExample(TestApplicationFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_form
     *
     * @mbg.generated Sat Dec 31 20:23:41 CST 2022
     */
    int deleteByExample(TestApplicationFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_form
     *
     * @mbg.generated Sat Dec 31 20:23:41 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_form
     *
     * @mbg.generated Sat Dec 31 20:23:41 CST 2022
     */
    int insert(TestApplicationForm row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_form
     *
     * @mbg.generated Sat Dec 31 20:23:41 CST 2022
     */
    int insertSelective(TestApplicationForm row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_form
     *
     * @mbg.generated Sat Dec 31 20:23:41 CST 2022
     */
    List<TestApplicationForm> selectByExample(TestApplicationFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_form
     *
     * @mbg.generated Sat Dec 31 20:23:41 CST 2022
     */
    TestApplicationForm selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_form
     *
     * @mbg.generated Sat Dec 31 20:23:41 CST 2022
     */
    int updateByExampleSelective(@Param("row") TestApplicationForm row, @Param("example") TestApplicationFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_form
     *
     * @mbg.generated Sat Dec 31 20:23:41 CST 2022
     */
    int updateByExample(@Param("row") TestApplicationForm row, @Param("example") TestApplicationFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_form
     *
     * @mbg.generated Sat Dec 31 20:23:41 CST 2022
     */
    int updateByPrimaryKeySelective(TestApplicationForm row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_form
     *
     * @mbg.generated Sat Dec 31 20:23:41 CST 2022
     */
    int updateByPrimaryKey(TestApplicationForm row);
}