package com.libiao.customer.dal.mapper;

import com.libiao.customer.dal.model.TestApplicationItem;
import com.libiao.customer.dal.model.TestApplicationItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestApplicationItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_item
     *
     * @mbg.generated Sun Jan 01 15:36:17 CST 2023
     */
    long countByExample(TestApplicationItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_item
     *
     * @mbg.generated Sun Jan 01 15:36:17 CST 2023
     */
    int deleteByExample(TestApplicationItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_item
     *
     * @mbg.generated Sun Jan 01 15:36:17 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_item
     *
     * @mbg.generated Sun Jan 01 15:36:17 CST 2023
     */
    int insert(TestApplicationItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_item
     *
     * @mbg.generated Sun Jan 01 15:36:17 CST 2023
     */
    int insertSelective(TestApplicationItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_item
     *
     * @mbg.generated Sun Jan 01 15:36:17 CST 2023
     */
    List<TestApplicationItem> selectByExample(TestApplicationItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_item
     *
     * @mbg.generated Sun Jan 01 15:36:17 CST 2023
     */
    TestApplicationItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_item
     *
     * @mbg.generated Sun Jan 01 15:36:17 CST 2023
     */
    int updateByExampleSelective(@Param("row") TestApplicationItem row, @Param("example") TestApplicationItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_item
     *
     * @mbg.generated Sun Jan 01 15:36:17 CST 2023
     */
    int updateByExample(@Param("row") TestApplicationItem row, @Param("example") TestApplicationItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_item
     *
     * @mbg.generated Sun Jan 01 15:36:17 CST 2023
     */
    int updateByPrimaryKeySelective(TestApplicationItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_application_item
     *
     * @mbg.generated Sun Jan 01 15:36:17 CST 2023
     */
    int updateByPrimaryKey(TestApplicationItem row);
}